### ISSUE TITLE
Get Circle mode working with touch devices

### ISSUE THREAD

**Issue by JamesLMilner** [JamesLMilner/terra-draw#106]
At the moment the Circle mode implementation will not work as it relies on the mouse move event to create the circle. 

We should potentially rethink the approach, or have some branching conditional logic to account for touch devices.

**Comment by SiqueiraD** [comment]
We need identify if device is mobile or not, correctly?

**Comment by JamesLMilner** [comment]
So here it's not just if the device is mobile, it's more if the device is a touch device (could be tablet, but also tablets and some laptops). Since touch devices don't have a concept of mouse move we need to account for this in the Circle mode. There's a few ways this could be approached, but it'd require some discussion.
