### ISSUE TITLE
[Documentation] Document which modes work on touch devices 

### ISSUE THREAD

**Issue by JamesLMilner** [JamesLMilner/terra-draw#107]
At the moment it is not clear that certain modes do not work on mobile/touch devices - we should look to document this. I would have to double check which modes do not work out the box, but at least Circle mode is not supported (see #106). I would assume rectangle mode suffers the same fate.

**Comment by dob9601** [comment]
Expanding on this, drawing lines/points/polygons doesn't seem to work in Chrome on touch devices - but do in Firefox

**Comment by JamesLMilner** [comment]
Hey @dob9601 thanks for sharing your experience. Could you potentially share more information about this as it doesn't sound intended! I am able to draw points lines and polygons on terradraw.io on Chrome on Android.

Can you share your exact device, OS and browser version so I can investigate? Also which adapter are you using Terra Draw with?

**Comment by dob9601** [comment]
Hey,
A friend and I came across the behaviour when looking at the demo hosted on the terradraw docs (https://terradraw.io/). On both devices, the behaviour was identical with it working on Firefox (Android) but not Chrome (also Android). 

I'm running `Chrome 120.0.6099.144` on Android 14 (Pixel 7)

**Comment by dob9601** [comment]
https://github.com/JamesLMilner/terra-draw/assets/24723950/8a54e63e-7dea-4e7f-ad73-69c57dbec99f

**Comment by JamesLMilner** [comment]
@dob9601 this is strange! Thank you for the info and the video, very helpful. I am also running Chrome 120 on Android and not seeing this issue weirdly. Let me do some more digging and get back to you. If you have any additional information you may help to debug please feel free to share in the meantime :)

**Comment by dob9601** [comment]
> @dob9601 this is strange! Thank you for the info and the video, very helpful. I am also running Chrome 120 on Android and not seeing this issue weirdly. Let me do some more digging and get back to you. If you have any additional information you may help to debug please feel free to share in the meantime :)

Not a problem! Feel free to reach out if you need any specific debug information

**Comment by JamesLMilner** [comment]
@dob9601 going to move this out a separate dedicated issue :)  #153

**Comment by JamesLMilner** [comment]
I've looked into this and it appears that Great Circle and Freehand are _not_ supported on mobile. Also Rectangle and Circle mode, although working, do not have as nice a UX as when using a mouse. I think supporting Great Circle shouldn't be too complicated, however freehand may require more thought. We could also potentially think about how we improve the UX for Rectangle and Circle mode going forward.
