### ISSUE TITLE
Is API docs page not latest?

### ISSUE THREAD

**Issue by onsummer** [JamesLMilner/terra-draw#11]
I have found no `TerraDrawOpenLayersAdaptor` API docs but there is source code indeed [src/adapters/openlayers.adapter.ts](https://github.com/JamesLMilner/terra-draw/blob/main/src/adapters/openlayers.adapter.ts)

**Comment by JamesLMilner** [comment]
Hey @onsummer thanks for raising this! Yes the docs had not been updated - appreciate you reminding me. I've updated and they are now live on terra-draw.io.
