### ISSUE TITLE
Clicking on controls should not draw features

### ISSUE THREAD

**Issue by jillro** [JamesLMilner/terra-draw#115]
Click on MapLibre zoom controls while TerraDraw is started is interpreted as a click on the map.

This seems to also be the case with Leaflet as one can test on https://terradraw.io/ :
* select Polygon mode
* try to click on zoom

**Comment by JamesLMilner** [comment]
Hi @jillro - thank you raising this, you are right this is not ideal behaviour. I will look into how we can hopefully resolve this.

**Comment by JamesLMilner** [comment]
I've started working on this and have a solution I think, but it will take a while for me to get it out due to other commitments. I will let you know when it's released.

**Comment by JamesLMilner** [comment]
@jillro thanks again for the bug report! 

I actually ended up going down a bit of a rabbit hole to fix this but think the solution was the right one :) The `terra-draw@0.0.1-alpha.49` release should fix this for you.

**Comment by jillro** [comment]
@JamesLMilner oh wow that was quick !

Thanks to you for this wonderful library.

**Comment by JamesLMilner** [comment]
@jillro no problem! Let me know if you have any more problems/feedback. Would love to chat more about what you're working on!
