### ISSUE TITLE
style: terra draw logo on dark backgrounds

### ISSUE THREAD

**Issue by morehawes** [JamesLMilner/terra-draw#125]
Hi!

I created a version of the logo [this PR](https://github.com/JamesLMilner/terra-draw/pull/124) which has a 5px white stroke around the word "Draw", so it displays better on dark backgrounds. GitHub supports "dark" mode which makes the word nearly invisible.

I figure there is probably an original somewhere, so just updating this might not be that helpful... but figured it was worth mentioning.

Cheers.

**Comment by JamesLMilner** [comment]
Hey @morehawes - thanks for raising this! I can see how that might not be a great experience in dark mode. Let me see what we can do! Will take a look at the new image you raised when I get a moment and try to work out what would be best. Appreciate your input here!

**Comment by JamesLMilner** [comment]
This is resolved now - thanks @morehawes !
