### ISSUE TITLE
How to determine clicked coordinates on select event?

### ISSUE THREAD

**Issue by scy** [JamesLMilner/terra-draw#131]
I've drawn a polygon, and then switched to select mode. Now I click that polygon to select it. The `select` event fires, but its only argument apparently is the feature ID of the polygon.

How can I find out _where_ on the polygon the user has clicked? I'd like to open a popup anchored to that spot.

The "best" workaround I can think of is:

* on `select`, remember the ID of the polygon and the intention to open that popup
* wait for the `click` event to bubble up to the map (in my case, MapLibre GL JS)
* in the handler for `click` (which knows the coordinates), check whether that "intention" to open a popup has been registered, and if so, do it now that you have both the ID and the coordinates

I was thinking about tracking the mouse movements and remembering the last pointer coordinates, but this won't work on touchscreens.

**Comment by JamesLMilner** [comment]
Hi @scy, thanks for raising this as it's a great question :)

I didn't actually have an immediate answer to this and had to think a little about it and try it out. There probably should be a more 'idomatic' way to make this happen and actually there may be a few solutions, such as the one you mentioned. The  'cleanest' solution I cam to was this:

```typescript
// Store a popup that we can reuse
let popup: maplibregl.Popup

// Register an on click event onto the map itself
map.on('click', (event) => {
	const snapshot = draw.getSnapshot()

	// Search the snapshot for the selected polygon
	const polygon = snapshot.find((feature) => feature.properties.selected === true && feature.geometry.type === 'Polygon')

	// If there is not selected polygon, don't do anything
	if (!polygon) {
		return
	}

	// Else create or update the popup location to be the cursor position!
	if (popup) {
		popup.setLngLat([event.lngLat.lng, event.lngLat.lat])
	} else {
		popup = new maplibregl.Popup({ closeOnClick: false })
			.setLngLat([event.lngLat.lng, event.lngLat.lat])
			.setHTML('<h1>Example Popup</h1>')
			.addTo(map);
	}
})
```

Let me know if this helps answer your question?

**Comment by scy** [comment]
Sorry @JamesLMilner, took me a few days to revisit this. Thanks for providing a detailed example!

I didn't know that there's actually a `selected` property available in the snapshot. That simplifies things indeed, and yeah, your solution works. I had to modify it slightly:

```typescript
onClick(e: MapMouseEvent) {
  // Look for a selected feature.
  const selected = this.draw!.getSnapshot().find(
    (feat) => feat.properties.selected,
  );
  if (!selected) {
    // Nothing is selected right now.
    return;
  }
  // When testing, e.lngLat was always offset by a fixed number of screen
  // pixels; not sure why. Using the coordinate conversion provided by Terra
  // Draw fixes this.
  const lngLat = this.adapter!.getLngLatFromEvent(e.originalEvent);
  // … do something with `selected` and `lngLat` …
}
```

No idea why I have to go through the whole `originalEvent` and `getLngLatFromEvent` dance, but the coordinates in `e.lngLat` (i.e. the MapLibre `MapMouseEvent`) were always off by a constant amount of screen pixels (32 in both the x and y direction), so it behaved as if I was clicking 32 pixels more to the left and to the top than I actually did, no matter the zoom level. I don't see any fancy CSS nonsense going on in my application, but maybe I missed something.

Still, I think it would be _way_ better if Terra Draw's `select` event provided me with some kind of original event that I could use to figure out the coordinates, either pixels or geo, of where the user actually clicked. I assume you're not providing this because the feature might have been selected through some other means (keyboard, programmatically, etc.), but for the cases where it makes sense, it would be super useful to have access to this.

**Comment by JamesLMilner** [comment]
@scy no problem, glad that the example helped. I appreciate this isn't super smooth - let me think about how we would handle this going forward. I say this as in the future we may open selecting up to alternative triggers apart from just clicking/taps (i.e. programmatically, with a keyboard, etc) and so a pointer event may not always be appropriate thing to pass through. This being said I still think we may be able to accommodate some version of this idea and can totally see why it would be helpful! 

I want to add the approach I sent through to you to the documentation in the mean time so there is at least _some_ documented way of achieving what you described as I do think it is probably a common pattern or approach that people want to do. Let me get onto that!

Any other thoughts/ideas feel free to let me know. Appreciate you trying out Terra Draw!
