### ISSUE TITLE
[Maplibre] Features of type Polygon can't be added via addFeatures with feature.properties.mode beeing "polygon"

### ISSUE THREAD

**Issue by iToXiQ** [JamesLMilner/terra-draw#135]
### Issue Summary
When attempting to add a polygon feature to the map using addFeatures and specifying the respective mode through feature.properties.mode, an error is encountered: Feature is not valid: "04d59530-ef0e-4642-a7f3-b907234556f3". However, if the feature is added in the "select" mode, it is displayed but becomes uneditable or movable.

### Replication 
https://stackblitz.com/edit/vitejs-vite-gmqk5m?file=src%2Fcomponents%2FMaplibre.vue
Change the mode of the polygon from "select" to "polygon" to encounter the error.

Here another replication with vanilla JS: https://jsbin.com/bisobap/edit?html,js,output

EDIT: It fails to validate the polygon feature as valid feature for the function call validate(feature) in src/terra-draw.ts:528

**Comment by iToXiQ** [comment]
Seems like setting coordinatePrecision is not respected across the package.
i.E. inside isValidPolygonFeature i am always getting  coordinatePrecision 9 instead of the specified one.

**Comment by JamesLMilner** [comment]
@iToXiQ thanks for raising this issue - I will look into it when I get a moment. I appreciate the reproduction steps, those will be helpful to debug. Would you mind kindly raising the coordinatePrecision issue in a separate issue so I can investigate that too?

**Comment by iToXiQ** [comment]
Will do so tomorrow - i will also try to resolve it and make a pr 👍🏻

**Comment by iToXiQ** [comment]
will close this now because issues come from coordinatePrecision and reopen new issue

**Comment by goto-w** [comment]
How can I solve this problem

**Comment by JamesLMilner** [comment]
@goto-w can you explain more about what you are doing and the error you are seeing ? Please feel free to open a new issue!

**Comment by goto-w** [comment]
@JamesLMilner I would like to ask which one I need to delete after drawing with the plugin terra-draw. How to deal with
