### ISSUE TITLE
TerraDraw coordinatePrecision is not respected inside TerraDraw<X>Mode || TerraDraw<X>Mode needs coordinatePrecision as additional param 

### ISSUE THREAD

**Issue by iToXiQ** [JamesLMilner/terra-draw#136]
### Issue Description
Currently when using TerraDraw modes like TerraDrawPolygonMode, the coordinatePrecision from the TerraDraw instance is not respected.

i.E.

when i create and add Modes of any Type they internally always have coordinatePrecision 9, because thats their default value. This is conflicting with the TerraDraw`s adapter, because when i am using an adapter which uses a precision of for example 14, features of precisions above 9 cannot be rendered ( besides of select mode).
```javascript 

// calls constructor of TerraDrawPolygonMode -> calls contructor of TerraDrawBaseDrawMode -> will set coordinatePrecision to 9 because there was no provided coordinatePrecision 
const polygonmode = new TerraDrawPolygonMode({
	snapping: true,
	allowSelfIntersections: false,
	// coordinatePrecision: 12, 
	// adding coordinatePrecision above will resolve the issue, but its not typed yet -> would be better to inject the coodinate precision from the terraDraw that is using it.
});

const draw = new TerraDraw({
	adapter: new TerraDrawLeafletAdapter(
		{
			lib: L,
			map,
			coordinatePrecision: 12,
		}
	),
	modes: [polygonmode]
});

```

**Comment by JamesLMilner** [comment]
Hello @iToXiQ - thanks for raising this, I can indeed see this being an issue. I saw your PR, I am a bit tied up before Christmas now but will try to find the time to review.

To give my immediate thoughts on this though; I think potentially that the `coordinatePrecision` should not be set at the mode level and instead should be managed by the adapter. It feels like it should probably be passed in the `register` function for the adapter in a similar way to the callbacks. Will share more thoughts soon!

**Comment by iToXiQ** [comment]
Yeah totally agree with that - will update my pr accordingly.
Have nice holidays c:
