### ISSUE TITLE
[Bug]: TerraDraw.clear() is unreliable and should probably be a Promise

### ISSUE THREAD

**Issue by iToXiQ** [JamesLMilner/terra-draw#139]
### Issue Description

When clearing the map with TerraDraw.clear(), the clearing is sometimes unreliable and features remain on the map.
For example after dragging a feature, and then clearing the map, some feature artifacts remain on the map.

### Reproduction
Small Example which renders a Polygon in Maplibre GL. When clicking on the EditMode Button, the same Polygon is rendered via TerraDraw. The button simply toggles between adding the feature to the map via TerraDraw, and clearing the map.

1. Toggle Edit Mode
2. Drag drawn TerraDraw polygon around a bit. Keep the polygon selected.
3. Toggle Edit Mode again.

Setting a timeout is also unreliable because it depends on how many features are rendered via TerraDraw( polygons need longer than points).

Vue3 : https://stackblitz.com/edit/vitejs-vite-zmfrj9?file=src%2Fcomponents%2FMaplibre.vue

Vanilla JS: https://stackblitz.com/edit/vitejs-vite-v4xsrl?file=src%2Fmain.ts

### Proposal
The clear function should return a Promise, and should respect features that are still in selected state.

Sorry for opening up so many issues :D

**Comment by JamesLMilner** [comment]
I can reproduce this bug - I think it is just an issue with the clear up function for MapLibre. Let me take a minute to look into it.
