### ISSUE TITLE
Users reporting issues drawing on mobile using Chrome 120 on Android

### ISSUE THREAD

**Issue by JamesLMilner** [JamesLMilner/terra-draw#153]
@dob9601 reported issues drawing on mobile via the Terra Draw website, https://terradraw.io in the #107 issue. We should investigate more to understand why this is not working.

FWIW I was not able to replicate this on my Android device running Chrome 120.

**Comment by JamesLMilner** [comment]
@dob9601 I've just bumped and rebuilt http://terradraw.io to run the latest version over Terra Draw (0.0.1-alpha.52). Could you try again on your device when you get a moment please? Thanks!

**Comment by dob9601** [comment]
I can confirm that it now functions perfectly across all modes on my device 🎉

**Comment by JamesLMilner** [comment]
Perfect 👍🏻
