### ISSUE TITLE
When will the official version be released?

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#162]

**Comment by JamesLMilner** [comment]
I assume you are asking when will it be out of alpha release? The main reason it is in alpha is the API has been slightly unstable as we figure out what it should look like. I think we should see a v1 release this year for sure, probably in the first half. I am thinking of pushing Terra Draw to beta status in the coming months

**Comment by Thunder7991** [comment]
Thank you, the author. In the past two days, I have provided you with the code for the issues I have discovered, or I can submit a PR myself.

**Comment by JamesLMilner** [comment]
I will close this issue as I've done my best to answer the original question. Thanks!
