### ISSUE TITLE
Can you add a public method to select a certain shape and then delete it?

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#164]

**Comment by Thunder7991** [comment]
![image](https://github.com/JamesLMilner/terra-draw/assets/61643801/fe5cb6f7-eb89-4208-b292-7beb74a19109)

In this case, the deletion will prioritize deleting the line segment  , deleting the point position again .
The correct approach would be to delete all graphics

**Comment by JamesLMilner** [comment]
Hi @Thunder7991 could you kindly clarify what you are trying to achieve and why? It is a bit hard for me to follow.

If you have a code snippet of what you are trying to do, or what your ideal code would look like this might help!
