### ISSUE TITLE
Can Selected geometries not have any color applied?

### ISSUE THREAD

**Issue by the-doctor-octo** [JamesLMilner/terra-draw#166]
Hello, 
I would like to know if there's a way to have no color applied to a geometry.
I have tried to set undefined to the style property, but the default blue color gets always applied. What I would like is to keep the original polygon color while this is selected.
Thank you for your time

**Comment by JamesLMilner** [comment]
Hey @the-doctor-octo - thanks for raising this issue. I am not sure I full understand the question, but let me do my best to point you in the right direction!

I will assume you are using this in conjunction with Polygon mode. You can set the styling of what should happen to selected polygons on the `TerraDrawSelectMode`. You use the following properties to do that:

```
	selectedPolygonColor: HexColorStyling;
	selectedPolygonFillOpacity: NumericStyling;
	selectedPolygonOutlineColor: HexColorStyling;
	selectedPolygonOutlineWidth: NumericStyling;
```

Where HexColorStyling is a Hex color (e.g. #660033) and NumericStyling is a number. With this you can configure the colour you want to change the selected polygon with `selectedPolygonColor`. In your case you can just set it to the same colour as whatever you styled the polygon color for `TerraDrawPolygonMode`.

Let me know if this answers your question?

**Comment by JamesLMilner** [comment]
@the-doctor-octo thanks again for the question - going to close this for now but if you have any other questions please feel free to raise another issue 👍🏻
