### ISSUE TITLE
Error when removing Sources and Layers in Maplibre

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#171]
There's an option i have to change the whole style of the map, basically to change the basemap. The problem is that it removes all sources an layers (including terra draw ones) to later set the new ones.

Of course if i go on as if nothing happened terra draw would throw an error saying theres no layers.

So to try to recreate terra draw layers i came up with this solution, 
```
// We get all the wanted features
const snapshot = this._terraDraw?.getSnapshot();
    
// Basically remove everything, store, sources and layers
this._terraDraw?.clear();
    
// Apply stored snapshot
this._terraDraw?.addFeatures(snapshot!);
```

The problem with this is that `clear` method would try to delete the sources and layers and since they are not there it will throw an error

`Error:  Error: Cannot remove non-existing layer "td-point".`

So is there a way to tell terra draw that the layers are already deleted?, or should I have a hardcoded list of sources and layers to avoid removing. Thanks for the clarification in the other issue. ❤️

**Comment by JamesLMilner** [comment]
Hey @alanOracle - Terra Draw Mapbox/MapLibre adapters work on the assumption that the library handles all the sources and layers relating to terra draw and that these aren't deliberately being mutated outside of the library. My recommendations would either be to:

1. Add the terra draw source/layers to the list to be ignored when you are are deleting all layers, as this will interfere with Terra Draws adapter internals
2. Use `start` and `stop` on the Terra Draw instance, as this will register and unregister all the layers and sources appropriately and it should be safe to do any operations once stopped.

Let me know if this makes sense?

**Comment by JamesLMilner** [comment]
Great - let me know if you get stuck!
