### ISSUE TITLE
"select" mode disables other component click events

### ISSUE THREAD

**Issue by marisancans** [JamesLMilner/terra-draw#174]
If im in "select" mode, my submit button is not working, because the click event is somehow hijacked?
Switching back to "polygon" mode allows me to save, but this is confusing for me as a user

![2024-01-24_20-50](https://github.com/JamesLMilner/terra-draw/assets/16538903/d496b462-44e6-492c-b1f9-ce841885647e)

**Comment by JamesLMilner** [comment]
Hey @marisancans - this sounds strange and not intended behaviour. I would probably need a small reproduction case to be able to debug exactly why that was happening. Would that be something you might be able to provide? Ideally as minimal a example as possible with the broken behaviour. 

Failing that could you have more information on what makes you think the click is being hijacked? Could you for example put a debugger/console.log on the Save button and check if it is being logged out or not? Terra Draw wouldn't really be able to hijack clicks outside of the map element, so maybe there is a possibility the map container is larger than the rendered map somehow? Let's keep digging!

**Comment by JamesLMilner** [comment]
@marisancans did you ever find out any more information about what might have been going on here?

**Comment by JamesLMilner** [comment]
I'm going to close this as I haven't heard back. Feel free to open a new issue with some reproduction steps if this is still a problem for you!
