### ISSUE TITLE
Google maps adapter requires an id

### ISSUE THREAD

**Issue by nerik** [JamesLMilner/terra-draw#176]
Hey there! Thank you for the fantastic work on this library.

We are using the Google Maps adapter with the <a href="https://visgl.github.io/react-google-maps/">`react-google-maps`</a> project. It does not require setting up an id for the map DOM element, however Terra Draw will throw an error when not setting it:

> Failed to execute 'querySelector' on 'Document': '# div[aria-label] .gm-style > div' is not a valid selector.

Here's a [CodeSandbox](https://codesandbox.io/p/sandbox/terra-draw-google-maps-forked-fdydfq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrt2ngar00063j6ewap9cogq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrt2ngar00023j6e8ek1puwb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrt2ngar00033j6e0qfz1r9v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrt2ngar00053j6ej4nux2a0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrt2ngar00023j6e8ek1puwb%2522%253A%257B%2522id%2522%253A%2522clrt2ngar00023j6e8ek1puwb%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clrt2ngar00053j6ej4nux2a0%2522%253A%257B%2522id%2522%253A%2522clrt2ngar00053j6ej4nux2a0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrt2ngar00043j6e8cnibm4w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrt2ngar00043j6e8cnibm4w%2522%257D%252C%2522clrt2ngar00033j6e0qfz1r9v%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrt2ngar00033j6e0qfz1r9v%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) showing the issue (you'll need to use your own Google Maps key)

Fails:
```
  const map = useMap();
  useDraw(map as any);
  return <Map zoom={6} center={{ lat: 55, lng: -5 }}></Map>;
```

Works:
```
const map = useMap("someID");
  useDraw(map as any);
  return <Map id="someID" zoom={6} center={{ lat: 55, lng: -5 }}></Map>;
```

Not sure this is the desired behavior, but might be worth adding a note in the docs if it is. Either way, I can have a look if you want.

**Comment by JamesLMilner** [comment]
Hey @nerik, great to hear from you, thanks for raising this issue. Apologies it took me a few days to get back to you - been a busy week! Appreciate the reproducible case on CodeSandbox, it's a nice touch!

Agree that perhaps we could tackle this two fold, first to update the docs to emphasise the `id` is a required attribute, and secondly to throw a more explicit error if the `id` is missing from the map element. I can resolve this today I think!

**Comment by JamesLMilner** [comment]
@nerik I think this should be remedied now by #178 . Let me know what you think!

**Comment by nerik** [comment]
@JamesLMilner Thank you, having an explicit error thrown will be super helpful for newcomers.
