### ISSUE TITLE
Maintaining rectangle features shape

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#183]
From someone else use case...

He draw some rectangles using rectangle mode.
Now he wants to edit some of them using select mode.

If he select one of the rectangles and then one of its selection points and drags it, then it will convert the rectangle into a polygon (i know it was always a polygon) but the rectangle shape will be gone.

So since these features already have the mode in its properties, hence we know those were created with rectangle mode, which means they were intended to be rectangles, why not on select mode maintain int's shape while dragging one of its vertexes.

This could be a flag that could be added for rectangle mode like 'mantainShape' or something like that.

This use case of terra draw is focused on bounding boxes so rectangle mode is perfect for these.

**Comment by JamesLMilner** [comment]
Hey @alanOracle nice to hear from you as always. I like this idea and I think another recently raised issue is similar to this. I like the solution you propose about `maintainShape` parameter - although I think we should pass to the select mode as this does the editing of the shape.

I think this will be a nice improvement - Thanks for the suggestion!

**Comment by JamesLMilner** [comment]
I've been working on this today - it's on the way!

**Comment by JamesLMilner** [comment]
This is now supported via `maintainShapeFrom`. You can either use `center` or `opposite` as possible parameters. For rectangles `opposite` will make more sense and for circle `center`.

Essentially this flag maintains the shape as you move the cursor, in relation to an origin. The origin for the `center` parameter is the center, and the origin for `opposite` is the opposite side of the bounding box of the geometry in question.

This is available in `0.0.1-alpha.56` 🎉

**Comment by alanOracle** [comment]
Awesome, thanks for the update definitely will check it out.
