### ISSUE TITLE
Editing status, clicking on other areas of the map will cancel the editing status

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#186]
![1706848066891](https://github.com/JamesLMilner/terra-draw/assets/61643801/a6e31702-83d8-4240-88da-b7d7a549f16b)
![1706849861299](https://github.com/JamesLMilner/terra-draw/assets/61643801/f43370d9-a435-42d4-87b2-cd137526129c)

Is it possible to click on other areas and still maintain the previous editing status?

**Comment by JamesLMilner** [comment]
We could potentially allow this as a feature, how would you want to deselect a feature? In this scenario you could only deselect by selecting another feature or exiting the mode. Would that be acceptable?

**Comment by Thunder7991** [comment]
I don’t know if my suggestion is correct. In the state of editing, click on the blank area of the map, you should keep the editing status. If you cancel it at this time, the user needs to click the map to enter the editing status again. Obviously this is repeated operation. If you click on the blank area to keep Edit state, I think it is the best.


As you said, if you want to cancel the selection function, you can only cancel the selection by selecting another function or exit mode.

In addition, I hope that the author can optimize the round/rectangle, the editing zoom, and maintain the original shape. If this problem can be solved, I think it can release the official version. Of course, I am also a source code of 'fork' a source code. Try to modify.

Thank you very much, I hope Terra-DRAW can be more complete.

**Comment by Thunder7991** [comment]
> We could potentially allow this as a feature, how would you want to deselect a feature? In this scenario you could only deselect by selecting another feature or exiting the mode. Would that be acceptable?

OK

**Comment by JamesLMilner** [comment]
I think that this can be resolved with https://github.com/JamesLMilner/terra-draw/pull/194 - the approach here is to add `allowManualDeselection` which can be set to `false` preventing the user from deselecting by clicking on other places on the map.

**Comment by Thunder7991** [comment]
Yes, it will be much simpler.

> I think that this can be resolved with #194 - the approach here is to add `allowManualDeselection` which can be set to `false` preventing the user from deselecting by clicking on other places on the map.

Yes, it will be much simpler.

**Comment by JamesLMilner** [comment]
This change is available on `0.0.1-alpha.57` 🎉 Hope it helps 👍🏻
