### ISSUE TITLE
Polygonal editing - bug

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#187]
When the polygon editor, the current point reaches 500+, it is impossible to drag and drag the point. Check the relevant data. Except for the same point as the first point and the last point, there is no abnormal.

![1706930277597](https://github.com/JamesLMilner/terra-draw/assets/61643801/6d3b43c2-8028-4924-917f-ddbe4d0f9c37)

**Comment by Thunder7991** [comment]
![image](https://github.com/JamesLMilner/terra-draw/assets/61643801/553fbce3-d5d7-464e-b502-ad2feb6ec69f)
The polygon is not edited as a whole, but you can delete the point above the red box to edit it

![image](https://github.com/JamesLMilner/terra-draw/assets/61643801/42d7562e-301c-42c3-a392-9e9d16fbf795)

**Comment by JamesLMilner** [comment]
@Thunder7991 thanks for raising an issue - I'm not sure I fully understand the first issue you raised. Could you try rephrasing it for me?

The second image you shared shouldn't be possible. Can you share how you achieved that?

**Comment by Thunder7991** [comment]
![image](https://github.com/JamesLMilner/terra-draw/assets/61643801/1d6774f3-c9a2-422e-a2fc-fcf11494aac9)

The current map environment is mapbox, the current graphic cannot be edited, Its point cannot be moved.

I must delete the abnormal points to make them a regular polygon (without intersecting positions), and the top image is the one I can edit after deleting the abnormal points

**Comment by Thunder7991** [comment]
When intersecting polygons appear during the drawing process, moving a vertex to release this state reveals that it cannot be moved.
