### ISSUE TITLE
Allow resizing of aspect ratio when dragging coordinates

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#191]
Hi @JamesLMilner thanks for adding this feature to terra draw I think its a great feature to have.

I was trying this new flag and I noticed that when using `opposite` in rectangles it successfully maintains its rectangle shape, however, it resizes the figure while maintaining its proportions as if I were resizing it using `ctrl + s`, only that it does it from the opposite vertex. 

I think the notion of taking the opposite vertex as the reference point to edit the rectangle is totally correct, but I think having a behavior similar to when you initially draw a rectangle (where you can easily modify its width-height proportion) would be more appropriate, instead of resize the feature maintaining its width-height proportion the same.

I clear example here would be...
Let say I draw almost a perfect square using the rectangle mode, 
then I realize I want to have that figure more like a rectangle where its width is considerably larger than its height,
with the current behavior this could not be possible.

Sorry if I didn't explain correctly what I meant by maintaining the shape of the feature and hope this makes sense. Thanks.

**Comment by JamesLMilner** [comment]
Hey @alanOracle - thanks for the feedback. What you're suggesting is possible, but it will take a bit of work to get it quite right. 

I'm thinking that `maintainShapeFrom` isn't a great property name here, and instead am going to change it to `resizeable`. It will allow for more options such as the one you are describing to allow for multi axis sizing.

**Comment by alanOracle** [comment]
@JamesLMilner Hey I've noticed that this behavior is now present in terra draw. Thanks for that. This feature fits almost perfectly with the bounding box editor use case Im trying to add.

Im using `resizable: 'opposite-planar'` and it seems to implement the feature described in this issue.

I do have some suggestions about this mode though. 

When you resize the rectangle in a certain way you can find this behavior where the corner you are trying to move is considerably off from the cursor.

https://github.com/JamesLMilner/terra-draw/assets/132691171/98efdd58-0e7e-4b31-8c92-e5f8073617ed

Also when you try to go to another axis you get this weird behavior

https://github.com/JamesLMilner/terra-draw/assets/132691171/98d512b2-1136-449b-b1b5-2c98f4393d77

I think a better approach would be to make sure the corner you are editing is right under the cursor at all times and also let the user edit the rectangle the way you draw a rectangle for the first time where you can cross axis with no problem

https://github.com/JamesLMilner/terra-draw/assets/132691171/9b5fbadb-2885-4176-bab8-d12b4e996b42

Thanks again and hopefully this suggestions make sense to you.

**Comment by JamesLMilner** [comment]
Hey @alanOracle  thanks for the feedback, I appreciate it. 

I noticed this bug with tracking the mouse cursor too, just about to raise a fix for this and will release a new release version. I also raised an issue for point you made about the axis. It should be resolvable 👍🏻 

Regarding making the resizeable option follow the behaviour of Rectangle mode; the resizeable option is not directly tied to the Rectangle mode and needs to support all mode and geometry types when selecting, so we need to be careful when thinking and modifying it's behaviour. This being said I totally understand the use-case here you are talking about and am trying to make it possible whilst still catering for lots of different other types of drawing modes 😄

**Comment by JamesLMilner** [comment]
I've raised 3 bug fixes that should improve the UX of the `resizeable` option. It's still not perfect, and I will raise a couple more bug tickets later on for two remaining issues I know about, but it should be much better than the last release :)

Will close this issue, lets cover any new bug/improvements in separate issues.
