### ISSUE TITLE
lib not accepted as an argument of adatper

### ISSUE THREAD

**Issue by ralexrdz** [JamesLMilner/terra-draw#195]
Hey, fellow

I'm trying to set TerraDraw on top of a react-map-gl/map-libre example on a Typescript-NextJs project like this:
terra version : `0.0.1-alpha55`

```javascript
import { MapLibreGL as lib } from "maplibre-gl";

import {
  TerraDraw,
  TerraDrawMapLibreGLAdapter,
  TerraDrawRectangleMode,
} from "terra-draw";

useEffect(() => {
    
    if (onMapLoad && mapRef?.current) {
      onMapLoad(mapRef.current);
      if (enableDraw) {
        
        const draw = new TerraDraw({
          // Using the MapLibre Adapter
          adapter: new TerraDrawMapLibreGLAdapter({ 
            map: mapRef.current.getMap(),
            lib
          }),
        
          // Add the Rectangle Mode
          modes: [new TerraDrawRectangleMode()],
        });

        console.log('draw',draw);       


        draw.start()
      }
    }
}, [onMapLoad, mapRef, enableDraw]);

``` 

I get a type error on lib saying this: 

`Object literal may only specify known properties, and 'lib' does not exist in type '{ map: Map; } & BaseAdapterConfig'.`

looking at TerraDrawMapLibreGLAdapter types definition, I don't see lib, and without it nothing happens

```typescript
export declare class TerraDrawMapLibreGLAdapter extends TerraDrawBaseAdapter {
    private mapboxglAdapter;
    constructor(config: {
        map: Map;
        /// NO lib?
    } & BaseAdapterConfig);
    

```

**Comment by JamesLMilner** [comment]
Hi @ralexrdz, thanks for raising this! You are right, there is no need to pass this in. I will update the guides, I think this was an oversight.

**Comment by JamesLMilner** [comment]
@ralexrdz just checking you didn't get this code from somewhere else other than the guides?

**Comment by ralexrdz** [comment]
It was from the guides, but I see it fixed, now

**Comment by JamesLMilner** [comment]
Yes I've updated it now. Thanks for your help!
