### ISSUE TITLE
Drawings disappear on map re-render (react-map-gl/maplibre) 

### ISSUE THREAD

**Issue by marisancans** [JamesLMilner/terra-draw#197]
When rendering just terra-draw and using memo its all good, but when I add a second children (markers) to render in map it causes  the map to re-render whenever the markers change and then all drawn items dissapear.

A simple setup for me looks like this:

```javascript
const { setEstates, estates, currentEstate } = useContext(ExplorePageContext);
const [geoJson, setGeoJson] = useState<FeatureCollection[]>([]);

  const drawings = useMemo(() => {
    return <TerraDrawing geoJson={geoJson} onFinish={handleGeoJsonChange} />;
  }, [geoJson]);

  const markers = useMemo(() => {
    return <Markers items={estates} />;
  }, [estates]);
  
  return (
     <GlMap>
          {drawings}
          {markers}
       </GlMap>
   )
```
Then after the drawn items dissappear and I try to draw something on map, when i click the map i get :
```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'setData')

Call Stack
a._setGeoJSONLayerData
node_modules/terra-draw/dist/terra-draw.modern.js (1:15369)
eval
node_modules/terra-draw/dist/terra-draw.modern.js (1:17641)
```

Here is how the GlMap looks like:

```javascript
import React, { memo } from "react";

import "maplibre-gl/dist/maplibre-gl.css";

import Map, {
  NavigationControl,
} from "react-map-gl/maplibre";

const GlMap = memo(({ children }) => {
  console.log("MAP RENDER");

  const mapStyle = {
    version: 8,
    sources: {
      osm: {
        type: "raster",
        tiles: [
          "https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}.png",
        ],
        tileSize: 256,
        attribution: "&copy; OpenStreetMap Contributors",
        maxzoom: 19,
      },
    },
    layers: [
      {
        id: "osm",
        type: "raster",
        source: "osm",
      },
    ],
  };

  return (
    <Map
      initialViewState={{
        latitude: 56.948719,
        longitude: 24.108638,
        zoom: 10,
      }}
      mapStyle={mapStyle}
      attributionControl={false}
    >
      {children}
      <NavigationControl showCompass={false} position={"bottom-right"} />
    </Map>
  );
});

export default GlMap;
```

Here is TerraDrawing

```javascript
import terraDrawSetup from "./terraDrawSetup";
import { useEffect, useRef, useState } from "react";
import { useMap } from "react-map-gl/maplibre";
import { TerraDraw } from "terra-draw";
import bbox from "@turf/bbox";

import { Switch } from "~/ui/switch";

const TerraDrawing = ({ geoJson, onFinish }) => {
  const [isDrawing, setIsDrawing] = useState(false);

  const { current: map } = useMap();
  const drawRef = useRef<TerraDraw>(null);

  const m = map?.getMap();

  const AddFeatures = () => {
    if (drawRef.current && geoJson && geoJson.length > 0) {
      drawRef.current.addFeatures(geoJson);
    }
  };

  useEffect(() => {
    console.log("load");
    if (!drawRef.current) {
      if (!m) return;

      const draw = terraDrawSetup(m);

      if (!draw) return;

      // draw.setMode("select");
      draw.start();
      draw?.on("finish", (ids: string[]) => {
        console.log("finish", ids);
        const features = draw?.getSnapshot();
        console.log("features", features);
        onFinish(features);
      });

      draw.setMode("polygon");
      drawRef.current = draw;
    }
  });

  useEffect(() => {
    AddFeatures();
  }, []);

  return (
    <div className="absolute left-0 z-10 flex items-center space-x-2 rounded bg-black p-2">
      <span className="rounded px-1 text-sm text-white">Edit</span>
      <Switch
        checked={isDrawing}
        onCheckedChange={() => setIsDrawing(!isDrawing)}
        className="text-white focus:outline-none"
      />
      {/* {JSON.stringify(geoJson)} */}
      <span className="rounded px-1 text-sm text-white">Draw</span>
    </div>
  );
};

export default TerraDrawing;

```

Here is terraDrawSetup:

```javascript

import {
    TerraDraw,
    TerraDrawMapLibreGLAdapter,
    TerraDrawSelectMode,
    TerraDrawPolygonMode,
} from "terra-draw";

import { MapLibreGL as lib } from "maplibre-gl";

const terraDrawSetup = (map) => {
    if (!map) {
        return
    }

    // Create Terra Draw
    const draw = new TerraDraw({
        // Using the MapLibre Adapter
        adapter: new TerraDrawMapLibreGLAdapter({ map, lib }),

        // Add the Rectangle Mode
        modes: [
            new TerraDrawPolygonMode(),
            new TerraDrawSelectMode({
                flags: {
                    polygon: {
                        feature: {
                            // The entire Feature can be moved
                            draggable: false,

                            // Individual coordinates that make up the Feature...
                            coordinates: {
                                // Can be added
                                midpoints: true,

                                // Can be moved
                                draggable: true,

                                // Can be deleted
                                deletable: true,
                            },
                        },
                    },
                },
            }),
        ],
    });

    return draw;
};


export default terraDrawSetup;
```

Im assuming that somewhere down the line the reference is lost because the map is re-rendered. Has anyone got such a problem before? How can I maybe fix it? Thanks

**Comment by JamesLMilner** [comment]
Hey @marisancans - I think your issue is to within your usage of React then with Terra Draw itself. Let me see if I can try and point you in the right direction.

It's hard to pin point exactly where the error you posted is arising from but if you want to see a working implementation with React, checkout the Terra Draw website code, specifically this file: https://github.com/JamesLMilner/terra-draw-website/blob/main/src/routes/home/index.tsx

I would probably suggest following that pattern of using `useMemo` rather than `useRef` here. The code you have with the useEffect will run every single render, which is unnecessary and is probably leading to the bug you're seeing.

This block is also suspicious, as it will only run once (empty dependency array) but there is no guarantee the map or Terra Draw instance is ready at that point in time:

```javascript
  useEffect(() => {
    AddFeatures();
  }, []);
```

Instead, you probably want something closer to:

```javascript
  const draw = useMemo(() => {
    if (map) {
      const terraDraw = setupDraw(map, L);
      terraDraw.start();
      return terraDraw;
    }
  }, [map]);

  useEffect(() => {
     if (draw && geoJson && geoJson.length > 0) {
      draw.addFeatures(geoJson);
    }
    
    // So that the original features are removed when the component is unmounted/the geojson changes
    return () => {
         draw.removeFeatures(geoJson.features.map((feature) => feature.id));
    }
  }, [terraDraw]);
```

Hope this helps!

**Comment by marisancans** [comment]
Hey, I refactored a lot based on your examples, thanks. It was still not working for me so I dig deeper.
Looks like react strict mode is causing a double render even on useMemo

  ```
const draw = useMemo(() => {
    var terraDraw: TerraDraw | null = null;

    if (m) {
      console.log("SETUP DRAW");
      terraDraw = setupDraw(m);
      terraDraw.start();
      terraDraw.setMode("polygon");
      setDrawInitialized(true);
      return terraDraw;
    }

    return null;
  }, [m]);
```

This memo is called twice, I don't want to disable strict mode because it just seems like a dirty fix and overall should not be disabled in development mode. Is there any ideas on how to handle it?

**Comment by JamesLMilner** [comment]
Thanks for the update - unfortunately it's hard to debug without a live environment like CodeSandbox etc. I am just looking through the code, a few thoughts:

* Need to ensure the draw instance hasn't already been set
* Need to check if the features haven't already been added (using `featuresAdded` to track this) otherwise will try and add the features multiple times
* Need to check if Terra Draw is enabled before calling `removeFeatures` 

This would be my changes, although I haven't run them:

```typescript
import setupDraw from "./terraDrawSetup";
import { useEffect, useRef, useState, useMemo, useCallback } from "react";
import { useMap } from "react-map-gl/maplibre";
import { TerraDraw } from "terra-draw";
import { GeoJSONStoreFeatures } from "terra-draw/dist/store/store";
import bbox from "@turf/bbox";

import { Switch } from "~/ui/switch";

const TerraDrawing = ({ geoJson, onFinish }) => {
  const [isDrawing, setIsDrawing] = useState(false);
  const [mode, setMode] = useState<string>("static");

  const [selected, setSelected] = useState<GeoJSONStoreFeatures | undefined>();
  const [features, setFeatures] = useState<GeoJSONStoreFeatures[]>([]);

  const [drawInitialized, setDrawInitialized] = useState(false);

  const [featuresAdded, setFeaturesAdded] = useState(false);

  const { current: map } = useMap();

  const m = map?.getMap();

  const draw = useRef<TerraDraw | null>(null);

  useEffect(() => {
    if (m && !draw.current) {
      console.log("SETUP DRAW");
      const terraDraw = setupDraw(m);
      terraDraw.start();
      terraDraw.setMode("polygon");
      setDrawInitialized(true);
      draw.current = terraDraw;
    }

    return () => {
      if (draw.current) {
        draw.current?.stop();
      }
    };
  }, [m]);

  const changeMode = useCallback(
    (newMode: string) => {
      if (draw) {
        const mode = isDrawing ? "polygon" : "select";
        draw.current?.setMode(mode);
      }
    },
    [draw]
  );

  useEffect(() => {
    draw.current?.on("change", () => {
      const snapshot = draw.current?.getSnapshot();
      if (snapshot) {
        setFeatures(snapshot);
        setSelected(snapshot.find((f) => f.properties.selected));
      }
    });
  }, [draw]);

  useEffect(() => {
    if (!featuresAdded && draw.current && geoJson && geoJson.length > 0) {
      draw.current?.addFeatures(geoJson);
      setFeaturesAdded(true);
    }

    // So that the original features are removed when the component is unmounted/the geojson changes
    return () => {
      if (draw.current && draw.current.enabled) {
        draw.current?.removeFeatures(geoJson.map((feature) => feature.id));
      }
    };
  }, [draw, geoJson]);

  return (
    <div className="absolute left-0 z-10 flex items-center space-x-2 rounded bg-black p-2">
      <span className="rounded px-1 text-sm text-white">Edit</span>
      <Switch
        checked={isDrawing}
        onCheckedChange={() => setIsDrawing(!isDrawing)}
        className="text-white focus:outline-none"
      />
      {/* {JSON.stringify(geoJson)} */}
      <span className="rounded px-1 text-sm text-white">Draw</span>
    </div>
  );
};

export default TerraDrawing;
```

Hope this helps!

**Comment by marisancans** [comment]
@JamesLMilner Is it ok if I prepare a repo that has devcontainer setup in it? I i'm always working in VScode devcontainer and it gives a great 1:1 sandboxed environment

**Comment by JamesLMilner** [comment]
@marisancans yes sure! That would work fine for me. I'll do my best to assist

**Comment by marisancans** [comment]
This should work in devcontainer out of the box, if something is not working for you i will fix it.

https://github.com/marisancans/terra-draw-help

Here is how I usually do stuff:
ctrl+shift+p openns command pannel and choose "Devcontainers: Rebuild and Reopen in Container"

1. Create javascript terminal (so you can use breakpoints)
![image](https://github.com/JamesLMilner/terra-draw/assets/16538903/7216e368-6b08-406e-ac74-6dc9bdd6bf3d)
2. Run: $ npm i
3. Run: $ npm run dev 
4. Launch web page
![image](https://github.com/JamesLMilner/terra-draw/assets/16538903/8b757746-dc24-41f6-9b86-b159a458430f)


Some info on repo
This is a trimed down version of my original repo (so there is less clutter)

This is where fake api call is generated:
![image](https://github.com/JamesLMilner/terra-draw/assets/16538903/01173154-a3d2-448f-bd5d-39a80f7e8467)

![image](https://github.com/JamesLMilner/terra-draw/assets/16538903/20cbff79-f72c-40b2-b6f4-fb5053b7e637)
![image](https://github.com/JamesLMilner/terra-draw/assets/16538903/697d525a-c6dd-495f-a162-f146b5b3188c)
![image](https://github.com/JamesLMilner/terra-draw/assets/16538903/53a02fa1-70a4-4914-91e0-cde818d88057)


I hope you have some spare time to check where the problem could be and maybe upgrade guides for next batch of users?

**Comment by JamesLMilner** [comment]
Hey @marisancans - I really appreciate you effort, but unfortunately it was too complex to set up the repo you provide in the limited time I have available this weekend. I'm sorry about that. However, I do really want to help you, so I've set up a really simple stripped back repo which you should be able to follow along with. It covers adding features works as expected and shows how you can do it reactively.

Here it is:

https://github.com/JamesLMilner/terra-draw-react-help

You can see why pass in the geojson from the parent component:

https://github.com/JamesLMilner/terra-draw-react-help/blob/main/src/components/app.tsx

Then we have a useEffect which triggers a setTimeout after 5 seconds, it changes the features.

The child component is able to re-render them fine with no errors:

https://github.com/JamesLMilner/terra-draw-react-help/blob/main/src/routes/home/index.tsx

I think if you are able to match this pattern is should all work okay! Let me know how you get on?

<img width="1710" alt="Screenshot 2024-02-25 at 16 18 31" src="https://github.com/JamesLMilner/terra-draw/assets/8822075/c356ca6d-ebe2-4ce2-bc84-3be72c47ce14">

**Comment by JamesLMilner** [comment]
I haven't heard back in a while so going to close this for now. Feel free to reopen with any new questions you might have.

**Comment by j0hnm4r5** [comment]
Just chiming in here for anybody that comes across this in the future:

The examples from @JamesLMilner are fantastic, but at least in React I too needed to set the `draw` instance with `useRef` and `useEffect` instead of `useMemo`. useMemo (unlike useEffect) doesn't have a cleanup callback, so in Strict mode (which is pretty much all the time in development with modern React frameworks) the library is loaded twice, resulting in a `Source "td-point" already exists` error whenever you try to draw.

I did something like this (similar to @marisancans):

```ts
import { useEffect, useRef } from 'react'
import { useMap } from 'react-map-gl/maplibre'
import { TerraDraw, TerraDrawRectangleMode } from 'terra-draw'
import { TerraDrawMapLibreGLAdapter } from 'terra-draw-maplibre-gl-adapter'

const ExampleComponent = () => {
  const { map } = useMap()
  const draw = useRef<TerraDraw | null>(null)

  useEffect(() => {
    if (map) {
      draw.current = new TerraDraw({
        adapter: new TerraDrawMapLibreGLAdapter({ map: map?.getMap() }),
        modes: [new TerraDrawRectangleMode()],
      })

      console.log('Starting TerraDraw')
      draw.current.start()
      draw.current.setMode('rectangle')
    }

    return () => {
      console.log('Stopping TerraDraw')
      draw.current?.stop()
    }
  }, [map])

  return <></>
}
```

With that, you should see the console log "Starting TerraDraw", followed by "Stopping TerraDraw", and then a final "Starting TerraDraw", and you should immediately be able to draw a rectangle on the map.

**Comment by nerik** [comment]
Slightly amended version of @j0hnm4r5's solution (with Mapbox GL) :
```
function Drawing() {
  const map = useMap();
  const draw = useRef<TerraDraw | null>(null);

  useEffect(() => {
    if (map?.current) {
      map.current.once("load", () => {
        if (!draw.current) {
          draw.current = new TerraDraw({
            adapter: new TerraDrawMapboxGLAdapter({
              map: map.current?.getMap(),
            }),
            modes: [new TerraDrawRectangleMode()],
          });

          console.log("Starting TerraDraw");
          draw.current.start();
          draw.current.setMode("rectangle");
        }
      });
    }

    return () => {
      console.log("Stopping TerraDraw");
      draw.current?.stop();
    };
  }, [map]);

  return <></>;
}
```

**Comment by JamesLMilner** [comment]
Thank you for sharing @nerik !
