### ISSUE TITLE
npm run serve

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#220]
@JamesLMilner Hi I find in the docs that you can run  `npm run serve` to easily try terra draw. However I tried it and it doesn't seems to exist anymore. Is there another command replacing this one to run the examples?

**Comment by JamesLMilner** [comment]
You need to run it in the `development` folder, it should work all okay. Let me update the docs to make that clearer.

**Comment by alanOracle** [comment]
ooops yeah you're right, sorry about that.
