### ISSUE TITLE
A method for real-time acquisition of circular radius

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#221]
Hey @JamesLMilner , I hope there can be exposed attributes or methods for obtaining real-time radius of circles.
During the drawing process, getsnapshot and turf cannot be calculated, resulting in an error message.

```typescript
draw.on('change', (e: string, type: string) => {
 if (e?.length && drawType == 'circle' && !['delete', 'create'].includes(type)) {
    getCircleDiameter(e[0])
  }
});

```
This is the radius method I currently use to calculate and draw circles.

**Comment by JamesLMilner** [comment]
Seems like a reasonable request 👍🏻  I've implemented it in the latest release
