### ISSUE TITLE
[Feature Request] Added polygon point adsorption function

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#238]
**Is your feature request related to a problem? Please describe.**
Hey👏 @JamesLMilner ，There is an extension function. When drawing a polygon, if there are other polygons (only polygons, excluding circles/lines) near the point, the current point can be adsorbed onto multiple deformations.

**Comment by JamesLMilner** [comment]
Currently this behaviour is outside the scope of the basic polygon mode. The polygon mode supports snapping which is a step towards what I think you're trying to do here. You may benefit from writing your own mode to support this behaviour. See an example of a custom mode here:

https://github.com/JamesLMilner/terra-draw-route-snap-mode
