### ISSUE TITLE
Circle editing status, fast scaling issue

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#243]
Hey,  @JamesLMilner . The new features have been used just now, and there are still some problems. The restrictions on the area are equivalent to the restrictions of the radius. I have implemented it in the test demo, but there is a problem. If you quickly move the mouse to enlarge and shrink, it can also be said that it can also be said that Pressure testing, he will break through this limit. For example, the area is 1,000 square meters, and occasionally less than 1000, which may be related to the execution process of the entire program.

The new version will still have irregular circles, and you need to trouble you to adjust.

_Originally posted by @Thunder7991 in https://github.com/JamesLMilner/terra-draw/issues/230#issuecomment-2076334277_

**Comment by JamesLMilner** [comment]
@Thunder7991 apologies I am struggling to understand the issue you are explaining. 

I have just released a fix for an issue I noticed with `resizable: "center-web-mercator"` and `resizable: "center-fixed-web-mercator" where resizing would gradually move the location of the polygon (potentially also deforming it?).

Let me know if version `0.0.1-alpha.65` helps your issue. If not, please can you reopen with a new description?
