### ISSUE TITLE
[Bug] Issue with right click to delete removing multiple coordinates whilst polygon/linestring editing

### ISSUE THREAD

**Issue by risusinf** [JamesLMilner/terra-draw#250]
While editing a polygon right-clicking a point to remove it also kills another point in the vicinity.

In the picture result of deleting a point via right-click (red circled) - point in the blue circle also gets removed.

![Screenshot_20240513_133837](https://github.com/JamesLMilner/terra-draw/assets/122530621/3477ecfd-28ed-441e-9f51-0e4bc2fe8945)

This doesn't happen when zoomed-in closely, so i assume it has something to do with pointer distance.

**Comment by JamesLMilner** [comment]
I can confirm that this is an issue I can replicate - I'll look into it when I get a chance.

**Comment by JamesLMilner** [comment]
This should be resolved now in `0.0.1-alpha.67` 🎉

**Comment by risusinf** [comment]
Seems to work as expected now. Thank you for quick resolve.

**Comment by JamesLMilner** [comment]
Great 👍🏻 Glad to hear it. What are you working on out of interest?

**Comment by risusinf** [comment]
Just a pet project, kind of a web map, that calculates and highlights geometry differences after editing, and stores history of changes in postgres. Some other features as well, in particular i use terradraw as base for advanced length and area ruler.

**Comment by JamesLMilner** [comment]
@risusinf cool, that sounds fun. I'm glad you finding Terra Draw useful! Feel free to open a new issue if you find any other bugs etc

**Comment by risusinf** [comment]
It is my first ever coding project so i am kind of proud of it for what is already capable of. Many things are probably done wrong or could be better, but i am figuring it out as i go on. Right now i'm trying to develop server side scripting to support features like registration.

TerraDraw is a great project, it is already much better than mapbox-draw which i attempted to use earlier. At this point it could not be even deployed properly with maplibre. So TD is invalueable.

Regarding other bugs i have couple of questions about things i can't get the way i want but those are not necessarily bugs. I could lay it out here while we at it if you don't mind.
