### ISSUE TITLE
Method to correctly remove terra draw

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#28]
Hi its me again, I hope you're doing well, now with suggestions, they are not really bugs since you can workaround them the way I will explain in the following...
Thanks again for sharing the project ❤️ 
# Update clear() method to correctly delete all features
Currently when you use the clear() method it just makes the store property to point to a new empty object. 

https://github.com/JamesLMilner/terra-draw/blob/9d33e5669f8629798909c77fe2f0a6e633957e07/src/store/store.ts#L279

But it seems that the previous store is being referenced someplace else since when you call this method it does not remove the features.

### CUERRENT WORKAROUND:
Use the delete() method of the store, passing it all the stored ids.
`terraDrawInstance._store.delete( Object.keys(terraDrawInstance._store.store) );`

# Method to delete sources and layers
Currently when using mapboxgl adapter some sources and layers are created by terra draw, with a certain id pattern.

https://github.com/JamesLMilner/terra-draw/blob/9d33e5669f8629798909c77fe2f0a6e633957e07/src/adapters/mapbox-gl.adapter.ts#L143

It would be nice to have a method to remove those sources and layers when the user is done using terra draw.

### CUERRENT WORKAROUND:
Deleting the sources and layers manually by...

Get the modes of the terra draw instance 
`const modes = Object.keys(terraDrawInstance._modes);`

Iterate over them removing first layers and then source for each of the feature types (point, linestring, polygon).

These are the sources and layers that are created for each mode:

layer `td-${mode}-point`
source `td-${mode}-point`

layer `td-${mode}-linestring`
source `td-${mode}-linestring`

layer `td-${mode}-polygon`
layer `td-${mode}-polygonoutline`
source `td-${mode}-polygon`

**Comment by JamesLMilner** [comment]
Hi @alanOracle - thanks for raising this! Yes I can see the problem here - `clear` does not actively remove any layers from the via the adapter so even though the store is emptied they will remain on rendered. Let me look at finding a cleaner way to do this so you don't need the work around!

**Comment by JamesLMilner** [comment]
Hi @alanOracle - this should be resolved now in version `0.0.1-alpha.30`. Now when you call clear it will tell the adapter to remove all layers/sources it has created.  Can you let me know if this resolves all your issues?

In the future I would like to add more specific methods, perhaps either as a parameter to `clear` or via specific methods like `clearMode('mode-name')`. Let me know if this sounds useful?

**Comment by alanOracle** [comment]
Awesome, yeah it works perfectly on my end now. Thanks James. 👍 

In my case, I treat all the modes as a one (a single style for all etc...) so specifically for me I wouldn't use such method in the near future, but I guess for the project could be a good addition.

**Comment by JamesLMilner** [comment]
Great, glad this change worked for you. I will close this for now - feel free to open another issue in the future if you find anything similar!
