### ISSUE TITLE
[Feature Request] 3 Click Rectangle Creation

### ISSUE THREAD

**Issue by ingalls** [JamesLMilner/terra-draw#286]
### Context

The current rectangle mode only allows creating rectangles that are aligned along the cardinal axis.

It would be awesome to either change the rectangle mode to allow 3 click rectangle creation to allow for rectangles on any axis or implement this in another mode.

An example of the behavior is given in the screenshot below courtesy of the JOSM Building Plugin.

[Screencast from 2024-07-26 14-37-27.webm](https://github.com/user-attachments/assets/413117da-6f62-4098-a22e-8ee35dda3851)

cc/ @JamesLMilner

**Comment by JamesLMilner** [comment]
This is now available in `1.0.0-beta.1` 🎉
