### ISSUE TITLE
Programmatic way to exit drawing mode when done drawing

### ISSUE THREAD

**Issue by bdon** [JamesLMilner/terra-draw#29]
What's the right way for me to end a drawing mode? Example use case: The user can either draw a rectangle or a polygon; when they have finished dragging the rectangle or closed the polygon, the mode should stop and the cursor should change back to the normal browsing/panning one (The library seems to swallow keyboard events while a mode is active too).

Thanks!

**Comment by JamesLMilner** [comment]
Hey @bdon - I was just looking at the API and you're right that there probably isn't a good way to do this right now. The default behaviour is to stay in the mode after geometry completion. 

The hack work around I came up with would be something like: 

```javascript
	draw.on("change", (_, type) => {
	    if (type === "created") {
		    polygonMode.stop();
	    }
	});
```

However, firstly I'd need to verify this works as expected (bit strapped for time at the moment), but also I think this isn't a great developer experience and also is probably error prone.

Some potential options would be to:

- Add a boolean parameter such as 'exitOnCreate' to the mode constructors which allows for this behaviour
- Work out if there's a way to make the the `draw.on('created'` approach nicer
- Provide event callbacks on modes themselves and look at seeing if there's a nice way of doing it that way

Let me have a think about this - also appreciate any thoughts you may have. Regarding the keyboard events, I assume you mean that it is swallowing them outside of Terra Draw i.e. you are adding a native event handler on the map DOM element and they are being swallowed there?

**Comment by bdon** [comment]
The way [Leaflet.Editable](https://github.com/Leaflet/Leaflet.Editable) handles this is via `commit:` events:

```js
map.on("editable:drawing:commit", e => setGeomFromDrawing(e))
```

I guess that assumes that all modes have a well-defined end point, but that might not be true for modes that have more complex interactions, like drawing a polygon and then drawing holes inside the polygon.

**Comment by bdon** [comment]
re: events, I think it has to do with the modes as well - I'm using https://github.com/maplibre/maplibre-gl-geocoder which exists as DOM elements on the map, and when I attempt to type in the geocoder while I'm in a mode it seems to get intercepted by the hotkeys.

**Comment by JamesLMilner** [comment]
@bdon I've add something similar to this now in version `0.0.1-alpha.31`. 

You can use it like this:

```javascript
	draw.on("finish", (id) => {
		// Feature if you need it
		const feature = draw.getSnapshot().find((feature) => feature.id === id);

		// Exit this drawing mode if necessary
		draw.setMode("static");
	});
```

Let me know if that works for you?

I tried to replicate the issue with the keys but I was not able to get the behaviour you're describing. The keyboards event seemed to come through to other event listeners regardless of the mode I was in. I will keep digging but if you have any more clues would be great to hear!

**Comment by bdon** [comment]
Yes, the `finish` event works perfect for what I'm trying to do. Thanks for that!

Still working on debugging the keypress issue

**Comment by bdon** [comment]
Here is a standalone HTML page that reproduces the problem:

When `draw.start()` is called, somewhere an event `preventDefault()` is happening that means the input element attached as a control at the top right doesn't respond. 

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="initial-scale=1,maximum-scale=1,user-scalable=no"
    />
    <script src="https://unpkg.com/maplibre-gl@3.0.0/dist/maplibre-gl.js"></script>
    <script src="https://unpkg.com/terra-draw@0.0.1-alpha.31/dist/terra-draw.umd.js"></script>
    <link
      href="https://unpkg.com/maplibre-gl@3.0.0/dist/maplibre-gl.css"
      rel="stylesheet"
    />
    <style>
      body {
        margin: 0;
        padding: 0;
      }
      #map {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
      var map = new maplibregl.Map({
        container: "map",
        style: "https://demotiles.maplibre.org/style.json"
      });

      class HelloWorldControl {
        onAdd(map) {
          this._map = map;
          this._container = document.createElement('input');
          this._container.className = 'maplibregl-ctrl';
          return this._container;
        }
         
        onRemove() {
          this._container.parentNode.removeChild(this._container);
          this._map = undefined;
        }
      }

      map.on("load", () => {
        const td = new terraDraw.TerraDraw({
            adapter: new terraDraw.TerraDrawMapLibreGLAdapter({
              map: map,
              coordinatePrecision: 9
            }),
            modes: {
              rectangle: new terraDraw.TerraDrawRectangleMode()
            }
        })
        td.start();
        td.setMode("rectangle");
      })
      map.addControl(new HelloWorldControl());
    </script>
  </body>
</html>
```

**Comment by JamesLMilner** [comment]
Thanks for this @bdon - I'm away for a few days but will take a look into this when I get back!

**Comment by JamesLMilner** [comment]
Just a short update - I managed to narrow this down. It seems this only applies to native events for elements inside the container. If the container is outside it does not swallow the event:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="initial-scale=1,maximum-scale=1,user-scalable=no"
    />
    <script src="https://unpkg.com/maplibre-gl@3.0.0/dist/maplibre-gl.js"></script>
    <script src="https://unpkg.com/terra-draw@0.0.1-alpha.31/dist/terra-draw.umd.js"></script>
    <link
      href="https://unpkg.com/maplibre-gl@3.0.0/dist/maplibre-gl.css"
      rel="stylesheet"
    />
    <style>
      body {
        margin: 0;
        padding: 0;
      }
      #map {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 100%;
      }
      #otherInput {
        z-index: 100000000000000;
        position: absolute;
        margin: 10px;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
      var map = new maplibregl.Map({
        container: "map",
        style: "https://demotiles.maplibre.org/style.json",
      });

      const otherInput = document.createElement("input");
      otherInput.id = "otherInput";
      document.body.appendChild(otherInput);

      class HelloWorldControl {
        onAdd(map) {
          this._map = map;
          this._container = document.createElement("input");
          this._container.className = "maplibregl-ctrl";
          return this._container;
        }

        onRemove() {
          this._container.parentNode.removeChild(this._container);
          this._map = undefined;
        }
      }

      map.on("load", () => {
        const td = new terraDraw.TerraDraw({
          adapter: new terraDraw.TerraDrawMapLibreGLAdapter({
            map: map,
            coordinatePrecision: 9,
          }),
          modes: {
            rectangle: new terraDraw.TerraDrawRectangleMode(),
          },
        });
        td.start();
        td.setMode("rectangle");
      });
      map.addControl(new HelloWorldControl());
    </script>
  </body>
</html>
```
However I can see for Mapbox controls and other similar widgets this will be painful. I may need to rethink how to handle this as the current default rotation/scaling key bindings are already used by the browser (control + r to rotate and control + s to scale). I could look at find a default intuitive keybinding that is not in use by the browser/mapping libraries or instead could make the `preventDefault` call configurable. Let me have a think what might make sense.

**Comment by JamesLMilner** [comment]
I'm closing this as the original core issue for exiting drawing mode now has a solution. I have opened #40 specifically for the keyboard events 👍🏻 I also think I have a reasonable fix for the issue!
