### ISSUE TITLE
[Chore] Signup as OS Geo Community Project

### ISSUE THREAD

**Issue by JamesLMilner** [JamesLMilner/terra-draw#295]
**What technical task needs doing?**
Terra Draw most likely qualifies as a OS Geo Community Project. This ticket is to track the progress of signing up to this program.

For more info see:

https://www.osgeo.org/projects/

cc @nickbearman

**Comment by nickbearman** [comment]
@JamesLMilner - once you have a OSGeo ID, you will need permissions to add stuff to the website. 

Please send something like this to:

I am currently sitting in on the OSGeo:UK code sprint with Nick and getting advice on the steps of adding a project to the website.

Following the notes on the incubation committee website I read that I need permission for my OSGeo userid [id] to create a project page.

I hope you can help with this.

**Comment by JamesLMilner** [comment]
@nickbearman I have signed up to the mailing list and sent an email to [incubator@lists.osgeo.org](mailto:incubator@lists.osgeo.org) following the Step 1 instructions here: https://wiki.osgeo.org/wiki/Incubation_Committee#Step_1:_Add_OSGeo_Website_Project_Page 

Can you let me know the next steps? I assume someone from OSGeo will ask any relevant questions on the mailing list? It looks like I can't currently signin on the OSGeo website 

<img width="892" alt="Screenshot 2024-08-28 at 19 57 12" src="https://github.com/user-attachments/assets/be223756-8a24-482c-895c-5edbf9250d55">

Is there anyone i can contact about resolving that?

**Comment by JamesLMilner** [comment]
@nickbearman the OSGeo wordpress login seems to have resolved itself!

**Comment by nickbearman** [comment]
Glad you are managing to progress this. The wordpress website is a bit weird at times but it sounds like you got there in the end. 

Please have a go at adding a page. Instructions on the Add a Project page are very welcome - I wrote them, so they need a run through and tidying up! Thanks

**Comment by JamesLMilner** [comment]
Hi @nickbearman I am just on holiday at the moment, but please let me know if there's anything else I need to actively do for this. I just replied to Jody's email about the header files but I need to get back to him regarding his other feedback but may need to wait till next week.

**Comment by nickbearman** [comment]
Thanks @JamesLMilner no nothing else you need to right now for this. When you're back is fine

**Comment by nickbearman** [comment]
Just seen your email to Jody. This is fine - he can answer to clarify what he is asking for

**Comment by JamesLMilner** [comment]
@nickbearman hope you're well. Am I right in thinking Terra Draw is now a OSGeo Community Project and I can close this issue? Thanks for all your help

**Comment by nickbearman** [comment]
@JamesLMilner I think the thread got diverted with your and Jody's discussion. 
I have poked people again for a decision. I think we should be there now. 
(I am still working out how the incubation committee works, sorry!)

Posted email at https://lists.osgeo.org/pipermail/incubator/2024-October/004926.html

**Comment by JamesLMilner** [comment]
@nickbearman thanks Nick, appreciated! Let me know if there's anything else. Do you know how many plus 1s are required?

**Comment by JamesLMilner** [comment]
Amazing, thank you @nickbearman - going to mark this as closed!
