### ISSUE TITLE
Performance Improvement on Mapbox/Maplibre adapters.

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#30]
I have noticed that I get a lot of lag while drawing with terra draw on maplibre (mapbox really since its the adapter that does everything).

For some reason it gets notoriously worse when you have the browser console open.

First I came to that conclusion since in the demo https://terradraw.io/ (it uses leaflet) it goes perfectly.

I was able to improve the performance notoriously locally and I'm going to explain all the process.

The idea is to reduce the most changes as possible to the maplibre sources and layers when handling the pointermove event (which is the most frequently fired)

I will start from the most impacting things

## Updating closing points
Is it really necessary to update the closing points every time the user moves the pointer?, I think this line could be deleted without impacting anywhere. And it improves the fluency of the movements a lot.

https://github.com/JamesLMilner/terra-draw/blob/157c1b3d375e3bd3bf78d0c713cb7f73a880af7e/src/modes/polygon/polygon.mode.ts#L224-L226

**This way instead of calling the _render() method of the adapter 2 times per movement now it should only be called once.**

## Only updating source if necessary
Currently all the sources are updated even if there wasn't any change on them. 

https://github.com/JamesLMilner/terra-draw/blob/157c1b3d375e3bd3bf78d0c713cb7f73a880af7e/src/adapters/mapbox-gl.adapter.ts#L366-L381

Why don't add a validation for each like
```
if(points.length || areDeleted)
if(linestrings.length || areDeleted)
if(polygons.length || areDeleted)
```

And of course define the `areDeleted` const at line 366, so that we would correctly delete features when needed.
`const areDeleted = changes.deletedIds.length;`

If we do this we should divide the features in changed and unchanged so that we **ONLY** update a source when there are changed features, and not every time we have unchanged (which is usual when user have draw different features already).

## Creating a lot of sources and layers
Right now for each mode terra draw creates 3 sources and 4 layers, so potentially if a user has all modes enabled there could be 30 sources and 40 layers being updated on each movement. 

There could be only 3 sources and 4 layers no matter the amount of modes.

Again, the most we can reduce the amount of sources and layers to update per movement the better.

I guess it was first created that way so that each mode would have its own layer potentially with its own different style.
But if that's true then each feature style is being described in its properties.
https://github.com/JamesLMilner/terra-draw/blob/157c1b3d375e3bd3bf78d0c713cb7f73a880af7e/src/adapters/mapbox-gl.adapter.ts#L318-L321
And then being styled based on those properties using maplibre expressions
https://github.com/JamesLMilner/terra-draw/blob/157c1b3d375e3bd3bf78d0c713cb7f73a880af7e/src/adapters/mapbox-gl.adapter.ts#L82-L83
So it seems like there is not really a need of having separate sources and layers per mode.

We could also delete the filters of all the layers
https://github.com/JamesLMilner/terra-draw/blob/157c1b3d375e3bd3bf78d0c713cb7f73a880af7e/src/adapters/mapbox-gl.adapter.ts#L76-L80

## Option to use maplibre outline instead of creating other layer
So far applying the above improvements the performance get much better but even having to update 2 layers it seems to cause a little bit of lag in maplibre, so the proposal is to have an option in maplibre adapter to avoid running this line.

https://github.com/JamesLMilner/terra-draw/blob/157c1b3d375e3bd3bf78d0c713cb7f73a880af7e/src/adapters/mapbox-gl.adapter.ts#L171

And instead use the outline of maplibre (which I understand is not highly customizable, but at least wont impact as much in the performance).

https://maplibre.org/maplibre-style-spec/layers/#paint-fill-fill-outline-color

And apply it here:

https://github.com/JamesLMilner/terra-draw/blob/157c1b3d375e3bd3bf78d0c713cb7f73a880af7e/src/adapters/mapbox-gl.adapter.ts#L82-L83

like: `"fill-outline-color": ["get", "polygonOutlineColor"]`

This way people could chose between the best performance or slightly worse but with better outlines.

## Results
Doing all this we dramatically reduce the amount of work have to be done by maplibre and the fluency of the movements.
| Description | Pointer Movement | Render Calls | Sources Updated | Layers Impacted |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| All modes enabled, current behavior | 1 | 2 | 30 | 40 |
| All modes enabled, fixed with outline in another layer | 1 | 1 | 1 | 2 |
| All modes enabled, fixed without outline | 1 | 1 | 1 | 1 |

Sending a PR for you to test it, and maybe use it to apply the changes by your own. Thanks for the help ❤️

**Comment by JamesLMilner** [comment]
Hi @alanOracle - thanks for raising this issue. I'm away for a few days but will look into it when I get back.

**Comment by JamesLMilner** [comment]
Hi @alanOracle - thanks again for raising this! Been looking into it a bit today. I've manage to implement some improvements to the Mapbox GL Adapter (and subsequently the MapLibre Adapter) - it's not totally perfect yet and I'm sure there's more that can be squeezed out of it but hopefully this is a good start for you.

In the future can I kindly request you refrain from making any more PRs with the change request? I appreciate these are small changes and but wanting to be overly cautious on the copyright side of things. Please feel free to keep raising detailed issues however, they are very much appreciated! I'd love to potentially set up a call/email thread at some point to understand more about your usage of Terra Draw :)

**Comment by JamesLMilner** [comment]
@alanOracle thanks again for your continued enthusiasm! 

I will make the small change to the update closing points as you suggested. I also have looked at determining if any feature of specific geometry typed has changed and have a branch that does that. However using the FPS meter I was not able to determine any measurable frame rate improvement. 

One thing to bear in mind now is that for the MapboxGL/MapbLibreGL Adapters is that they should now only be doing one render per frame as they only the last call to `render` is committed to the screen via the `setData` function. This means that even if we call `render` 100 times in a frame from within Terra Draw, only the last `render` call with be applied.

After this change I have seen similar FPS characteristics to the other Adapters like Leaflet, OpenLayers which all seem to operate at the 60FPS mark limit. This can be demonstrated in the short video below, see the top left for the FPS meter in Chrome. MapboxGL/MapbLibreGL  are maps 3 and 4 going from left to right - you'll see the FPS meter stays at 60 for both drawings. 

https://github.com/JamesLMilner/terra-draw/assets/8822075/fa860ccd-3291-47b6-9fed-6aa33f28fa79

If you can find a specific case where this is not staying true, please let me know and I'll see if we can fix it!

**Comment by alanOracle** [comment]
No, everything related to performance looks good now, thanks.

**Comment by JamesLMilner** [comment]
I will close this for now - happy to open new issues about this if there are specific problems again in the future :)
