### ISSUE TITLE
[Feature Request] Provide snapping to lines as well as coordinates in polygon mode

### ISSUE THREAD

**Issue by sahitono** [JamesLMilner/terra-draw#307]
**Describe the bug**
Using TerraDrawPolygonMode with snapping enabled cause unexpected behaviour on the mouse move of first point. the expectation is to have the mouse move of first point to snap too. but nothing snapped on the mouse move of first point

i think this could be fixed by removing these lines
https://github.com/JamesLMilner/terra-draw/blob/4ad84741130fc88ad08f42b8788e82f91bc2a83f/src/modes/polygon/polygon.mode.ts#L169-L171

**Terra Draw npm version**
1.0.0-beta.0

**To Reproduce**
1. Create `TerraDrawPolygonMode` with snapping enabled
2. Insert polygon with `setFeature`
3. `setMode` to polygon
4. Move mouse to the edge and vertex of polygon

**Expected behavior**
It should snap on polygon on mouse move even though it is not clicked yet

**Screenshots**
- 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: 130

**Smartphone (please complete the following information):**
tested on desktop only

**Additional context**
-

**Comment by JamesLMilner** [comment]
Hey @sahitono! Thanks for raising this - I can replicate this and I'm going to try and fix it.

What are you working on out of interest? 😄

**Comment by JamesLMilner** [comment]
Hey @sahitono - thanks for your interest in the project! What are you working on?

Can you explain what you mean by your expectation `to have the mouse move of first point to snap too`? Before the first point is draw there is just the mouse cursor so I am struggling to understand what you would be expecting to snap?

The first drawn point currently does snap as you can see from this video:

https://github.com/user-attachments/assets/6feebd11-f59e-4b8f-8ee6-9f91c93fe200

.

**Comment by sahitono** [comment]
Hi @JamesLMilner, thank you for creating an amazing library. What I meant by "snap" is something like the snap feature in OpenLayers, as shown in this example: https://openlayers.org/en/latest/examples/snap.html.

https://github.com/user-attachments/assets/add47dc4-305a-428c-8868-0b03ae1abb3d

**Comment by JamesLMilner** [comment]
@sahitono thanks for confirming how you would expect the snapping behaviour to work and showing how it currently works in OpenLayers. Apologies on the delay in responding, been a bit busy the last couple weeks. I'm going to have a think about this and see if there's a way to improve the existing snapping behaviour more broadly - will update when I've gathered my thoughts. Appreciate your input here!

**Comment by JamesLMilner** [comment]
@sahitono this should be possible now in `1.0.0-beta.11` via the  snapping `toLine` property in polygon and linestring modes, which is used like so:

```typescript
  new TerraDrawPolygonMode({
    snapping: {
      toLine: true,
      toCoordinate: true,
    },
    validation: (feature, { updateType }) => {
      if (updateType === "finish" || updateType === "commit") {
        return ValidateNotSelfIntersecting(feature);
      }
      return { valid: true };
    },
  })
```

Thank you for raising!
