### ISSUE TITLE
[Feature Request] Edit circles as circles, rectangles as rectangles

### ISSUE THREAD

**Issue by neodescis** [JamesLMilner/terra-draw#323]
Currently, it seems that while circles and rectangles can be created, they cannot be edited without misshaping them. That is, when you drag a point that is part of a circle, the shape is no longer a circle. When you drag a point that is part of a rectangle, the shape is no longer a rectangle.

I think that shapes created as circles should have four drag points, as suggested in #208 , but beyond that, dragging one of those drag points should resize the circle. The same should happen for a rectangle or angled rectangle: dragging one of a rectangle's corner drag points should resize the rectangle. Additionally, maybe a an angled rectangle could be rotated somehow while editing?

For some additional context, this is how this third-party mapbox draw set of modes for creating and editing circles works:  https://github.com/iamanvesh/mapbox-gl-draw-circle

We are currently using mapbox draw in our application, we have adopted the above circle mode, as well as a rectangle mode, and have gotten editing for both to work as I described above. I would love to replace it with terra-draw, but we will be unable to do that until terra-draw can support editing circles and rectangles similarly. Do you think this is something that could be added?

**Comment by neodescis** [comment]
Scratch this... I think it must be an issue with the maplibre-gl-terradraw library? At least resizing of rectangles appears to work on the terra-draw site.

**Comment by JamesLMilner** [comment]
@neodescis thanks for raising - I think perhaps this is just a case of changing the default select mode settings in `maplibre-gl-terradraw` to the more 'natural' settings. For rectangle you may want 'resizeable: 'opposite'` and `resizable: 'center'` for circle to match the drawing behaviours.

That might look a little something like this:

```typescript
 new TerraDrawSelectMode({
   flags: {
    circle: {
      feature: {
        draggable: true,
        coordinates: {
          resizable: 'center'
        }
      },
    },
    rectangle: {
      feature: {
        draggable: true,
        coordinates: {
          resizable: 'opposite'
        }
      }
    },
  },
})
```

I can speak to Jin about maybe making that the default upstream, but you could also use Terra Draw directly to achieve this. Let me know if you have any additional questions!

**Comment by neodescis** [comment]
Yep, I kept digging and discovered the options you posted. It does seem like they should be the defaults to me, but that's certainly less of an issue. Thank you!
