### ISSUE TITLE
[Bug] draw.addFeature with double precision array will throw error

### ISSUE THREAD

**Issue by taminhluan** [JamesLMilner/terra-draw#324]
**Describe the bug**
I tested on OpenLayerAdapter,

**Terra Draw npm version**
"terra-draw": "^1.0.0-beta.1",

**To Reproduce**
``` javascript
draw.addFeatures({
      "type": "Feature",
      "properties": {
        "mode": "polygon"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-1.82645, 51.17888999999], // 51.17888 -> will work
            [-1.826208, 51.179025],
            [-1.825859, 51.178867],
            [-1.82609, 51.178682],
            [-1.82645, 51.17888999999] // 51.17888 -> will work
          ]
        ]
      }
    })
```

**Workaround**
Modify geometry coordinates by nested trim precision of array
```
{
      function nestedMap(arr, callback) {
        return arr.map(item => 
          Array.isArray(item) ? nestedMap(item, callback) : callback(item)
        );
      }
      let trimmedNumbers = nestedMap(feature['geometry'].coordinates, num => parseFloat(num.toFixed(3)));
      feature['geometry'].coordinates = trimmedNumbers;
}
```

**Comment by JamesLMilner** [comment]
Hey @taminhluan, thanks for your interest in the project!

I think this is working as intended and not in fact a bug. The default `coordinatePrecision` which controls the level of allowed precision to be stored inside Terra Draw is set to 9, where as 51.17888999999 has 11 decimal places of of precision. [9 decimal places is microscopic level precision](https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude), so 11 places is unnecessary. 

You have a couple of options, you can do what you are currently doing and trim down the precision, or you can increase the `coordinatePrecision` parameter to say 12, although I would not recommend this as it means you will store more information that is necessary. I hope this makes sense!

**Comment by taminhluan** [comment]
Yes, Thank you

**Comment by JamesLMilner** [comment]
@taminhluan no problem! Glad I could help
