### ISSUE TITLE
[Feature Request] Sector and/or Sensor Modes

### ISSUE THREAD

**Issue by ingalls** [JamesLMilner/terra-draw#326]
Hey @JamesLMilner Thanks a ton for awesome AngledRectangle mode. Was super easy to get this out and folks are loving it as it is useful for quick rough building footprints when doing evacuation orders for wildland fire.

The feature requests never stop however and I'm wondering about the ability to draw "Sectors" or "Sensors" as part of our workflow to input new Wildfire and Highway Accident/Weather monitoring cameras into the system. Right now we have the URL of cameras that have been provided but need to geospatially orient their actual Field-Of-View.

![image](https://github.com/user-attachments/assets/ec435250-ef59-464a-9bfc-356260bbcdba)
_Example of current video support_

I use the term Sensor to describe a 4 point arc vs a sector being a "pie",

Sector - Generated by 3 clicks. Origination, Radius, and then arc
Sensor - Generated by 4 clicks, Origination, Radius from origination, Radius, and then arc

Examples Below drawn manually using the Polygon mode.

![image](https://github.com/user-attachments/assets/2d0a7c8a-40eb-4053-a572-f69f0df8f159)

**Comment by JamesLMilner** [comment]
For those following along, Terra Draw now exposed TerraDrawSectorMode in `1.0.0-beta.3` 🎉 

I am currently looking at TerraDrawSensorMode and we aim to have this available soon for users to try out.

**Comment by JamesLMilner** [comment]
Hey @ingalls 👋🏻 A little update for you here, `TerraDrawSensorMode` should now be exposed in `1.0.0-beta.4` for you to try out. I'd be interested to hear what you think about the drawing experience.

Here's it working across the different adapters:

![375948299-4ad33472-ae67-4759-9c0a-87d637821a90.png](https://github.com/user-attachments/assets/f269573c-db44-465b-af27-a8fadcef1c5c)

**Comment by JamesLMilner** [comment]
I actually just noticed one thing that might be an issue which is you can't style the circular line that gets drawn on the second mouse click. Let me get that resolved and do another release.

**Comment by JamesLMilner** [comment]
`1.0.0-beta.5` is now released which fixes the styling issue and also a small issue with the smoothness when transitioning the cursor into the inner radius of the donut.

**Comment by JamesLMilner** [comment]
@ingalls interested to hear how you got on with both of these modes 🙂 Let me know if there's any feedback or if these features can be considered complete as is?

**Comment by ingalls** [comment]
@JamesLMilner Hey! Sorry bust last couple weeks. These are literally perfect, deployed them as they came out! Our users were stoked above the Sensor drawing especially. I've got to talk to my boss about next steps but personally my brain is thinking about snapping. I'll email you when I have news :)
