### ISSUE TITLE
[Bug] TerraDrawLineStringMode does no clean up not cleanup closing point

### ISSUE THREAD

**Issue by bochkov-vi** [JamesLMilner/terra-draw#340]
The TerraDrawLineStringMode does not correctly clean up the closing point

Steps to reproduce the behaviour:
1. Go to 'https://terradraw.io/'
2. Click on line button
3. Start draw the line and press ESC
4. See closing point on the map

In:

`terra-draw/src/modes/linestring/linestring.mode.ts:492`

```typescript
this.closingPointId = undefined
```

```typescript
this.store.delete([this.closingPointId]);
```

**Comment by JamesLMilner** [comment]
Thanks! Will be resolved in next release
