### ISSUE TITLE
[Feature Request] Terra Draw does not expose enough types to create custom Adapter

### ISSUE THREAD

**Issue by bochkov-vi** [JamesLMilner/terra-draw#342]
I want to develop my own adapter, but there are not enough types to import, this becomes possible only if I tighten the entire terra-draw code to my project

**Comment by JamesLMilner** [comment]
Thanks for raising - I will try to look into this at some point soon.

**Comment by bochkov-vi** [comment]
now the type of TerraDrawCallbacks is missing

**Comment by JamesLMilner** [comment]
I'll look at trying to expose this for the next release. Thanks

**Comment by JamesLMilner** [comment]
This will be resolved in the next release, setting as closed. Let me know if there's anything else missing!
