### ISSUE TITLE
[Feature Request] Draw the circular shape, the radius can be drawn according to the specified value increase or decrease.

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#352]
Draw a round shape with a radius of 1500 meters. When you drag, you cannot accurately reach the execution radius. If the value of the value is set to 100, then it will become very easy.

**Comment by JamesLMilner** [comment]
Hey, I'm sorry I'm not sure I totally understand what is being asked here. I think you're asking that you want resizing to allow for changes in specific geodesic measured increments i.e. you want to create/resize in increments of say 100 meters? In honesty this would be quite complex and I think is probably outside the core scope. 

I think you could definitely achieve this using custom modes if that's something you wanted to explore.

**Comment by Thunder7991** [comment]
> Hey, I'm sorry I'm not sure I totally understand what is being asked here. I think you're asking that you want resizing to allow for changes in specific geodesic measured increments i.e. you want to create/resize in increments of say 100 meters? In honesty this would be quite complex and I think is probably outside the core scope.
> 
> I think you could definitely achieve this using custom modes if that's something you wanted to explore.

Thank you very much

**Comment by JamesLMilner** [comment]
This really depends on your specific requirements, but if you only want to allow changing of a circle within two specific sizes, you could do that with something like this based on area:

```typescript
new TerraDrawSelectMode({
    flags: {
    polygon: {
        feature: {
            validation: (feature) => {
                return ValidateMinAreaSquareMeters(feature, 1000000) && ValidateMaxAreaSquareMeters(feature, 2000000) 
            }
        }
    }
})
```

If you wanted diameter, you could adjust the function to calculate the circle diameter to ensure it was in between two given numbers.

I will close this as my belief is it can be achieved using the `validation` function and some custom logic which can be provided by the developer.
