### ISSUE TITLE
[Bug] Draw line cannot cross itself

### ISSUE THREAD

**Issue by y3nd** [JamesLMilner/terra-draw#354]
**Describe the bug**
When using the line tool, the point is not placed on click when it is crossing the current line being created/edited.

Tested on MapLibre

**Comment by y3nd** [comment]
This issue might be related to the self-intersecting polygon prevention

**Comment by JamesLMilner** [comment]
I am not able to reproduce this without enabling specific validations. For example you can enable this by doing:

```typescript
		new TerraDrawLineStringMode({
			validation: (feature, { updateType }) => {
				if (updateType === "finish" || updateType === "commit") {
					return ValidateNotSelfIntersecting(feature);
				}
				return true;
			},
		}),
```

Can you share the code with me you are using? Thanks

**Comment by JamesLMilner** [comment]
@y3nd I didn't hear back here so going to assume you managed to resolve the problem. As I mentioned I wasn't able to reproduce - as you mention it is probably that the example you're looking at uses some validation to prevent self intersection. Please feel free to raise another issue if you are still having problems, providing a reproduction case so I can take a look.
