### ISSUE TITLE
Freehand LineString mode

### ISSUE THREAD

**Issue by JamesLMilner** [JamesLMilner/terra-draw#36]
Just creating this ticket so it doesn't get lost - @kuanb suggested a Freehand LineString tool similar to the Freehand Polygon mode that is available. This would be reasonably straight forward to implement - there question of if it should also be a 'core mode' or handled externally.

**Comment by JamesLMilner** [comment]
There hasn't been any additional demand for this feature, and as such is unfortunately not a high priority for the project _currently_ so I will close this. Potentially we can look at this again in the future, especially if additional requests come in!

**Comment by EduCollin** [comment]
I find it incomprehensible how there is not more demand for this. Turning a 3D world map into a canvas seems to me like the coolest idea. One could draw military arrows, lines of commerce, icons and shapes... Whatever else too...

**Comment by CaraCodeDev** [comment]
I actually really want this, i have a client that wants to scribble on maps with his stylus.

**Comment by JamesLMilner** [comment]
@kuanb @EduNauta @ClickSnd I started experimenting with this a little this evening. I'll see if it's something we can add soon as it's less work that I anticipated 😅 

https://github.com/user-attachments/assets/3f796490-a9e3-4900-8096-ddeff506aa07

**Comment by CaraCodeDev** [comment]
Ah sweet! Yeah I was already trying to make my own solution and was close but it’s still closing the shape as if it was a polygon. 

Looking forward to this!

**Comment by EduNauta** [comment]
@JamesLMilner this is the good work. If you want more ideas on how to implement features and functionalities, look at what scribblemaps.com has to offer. They are very ahead from everyone. Their CEO Jonathan Wagner is very open to speak via linkedin.

**Comment by JamesLMilner** [comment]
This is now available via TerraDrawFreehandLineStringMode in version `1.11.0` 🎉

**Comment by CaraCodeDev** [comment]
A million thank yous!

**Comment by EduNauta** [comment]
@JamesLMilner i just used your library with freehand. Very cool! As i'mnot a programmer, i used cursor pro to mount an index.html website with your library and a googlemaps API to test this. From what i see, the freehand tool automatically wants to create a polygon. Wouldn't it be better to have 2 options, freehand string and freehand polygon? 
Cheers and immense thank yous for your work already done.

My dream of drawing on a 3D map has become true. Only with Mapbox though, Googlemaps uses 2.5D only for API embeddings. Look how cool this looks:

<img width="1882" height="1186" alt="Image" src="https://github.com/user-attachments/assets/f9bcca7f-9551-4a14-b705-e0055f86360f" />

**Comment by CaraCodeDev** [comment]
This is the feature he just added! Try the new freehand-linestring mode! Give cursor the link to the MODES documentation so it can add it for you. 

> [@JamesLMilner](https://github.com/JamesLMilner) i just used your library with freehand. Very cool! As i'mnot a programmer, i used cursor pro to mount an index.html website with your library and a googlemaps API to test this. From what i see, the freehand tool automatically wants to create a polygon. Wouldn't it be better to have 2 options, freehand string and freehand polygon? Cheers and immense thank yous for your work already done.
> 
> My dream of drawing on a 3D map has become true. Only with Mapbox though, Googlemaps uses 2.5D only for API embeddings. Look how cool this looks:
> 
> <img alt="Image" width="1882" height="1186" src="https://private-user-images.githubusercontent.com/122028894/471603018-f9bcca7f-9551-4a14-b705-e0055f86360f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM3NTUxMzEsIm5iZiI6MTc1Mzc1NDgzMSwicGF0aCI6Ii8xMjIwMjg4OTQvNDcxNjAzMDE4LWY5YmNjYTdmLTk1NTEtNGExNC1iNzA1LWUwMDU1Zjg2MzYwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyOVQwMjA3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjc3OTg2NGIwZmMzNTk2MjcyZjg3ZDBlYjg0YmE0ZDIyYWUzMWViMmI5NmRmMjg2MjU5YjI5MzM0NDYxODk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j-LYrTgpD0N3xO43wPybYL0DhonfraslJ9ws3629hkU">
