### ISSUE TITLE
[Bug] Circle Mode draws a circle of size 0 and ignores minimum starting radius if there is no cursor movement

### ISSUE THREAD

**Issue by Thunder7991** [JamesLMilner/terra-draw#369]
**Describe the bug**
Draw the circular, set the Startingradiuskilometers property, draw abnormal prototype, and double -click to end the drawing graphic abnormality disappear
**Terra Draw npm version**
main

**To Reproduce**

**Expected behavior**
The radius that starts drawn is that the previous version should be the minradius attribute. After double -clicking the drawing, the current graphic is retained.

**Screenshots**

https://github.com/user-attachments/assets/07001996-2e6b-48f2-93d4-46221f8667d5

**Comment by JamesLMilner** [comment]
Hey apologies as I'm not fully sure I understood your message. Judging by the video the issue seems to be to do with the way the circle 'disappears' on the second click when there is no mouse movement? In which case #370 should resolve this.
