### ISSUE TITLE
Personalization

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#38]
## Dashed Lines / Outlines
It would be nice to add a way to set the outlines of the features as dashed lines with a custom array like 
https://maplibre.org/maplibre-style-spec/layers/#paint-line-line-dasharray

## Cursor style
An option to let the user choose which cursor style wants. This because I think is better to have the `move` style
![image](https://github.com/JamesLMilner/terra-draw/assets/132691171/e06ec01a-3ee9-4d6e-90d7-a78e1de4036f)
when hovering a selected future in select mode. Also, to display this style ONLY when hovering the selected feature.

**Comment by JamesLMilner** [comment]
@alanOracle thanks for suggesting - I will see how realistic this would be when I get some time. One thing I've tried to ensure is approximate uniformity in styling across the different providers so would want to try and keep this property where possible. Let me see what I can do!

**Comment by JamesLMilner** [comment]
I will close this of favour of individual issues that can be tracked #48 and #49
