### ISSUE TITLE
[Bug] Polygon Mode broken in b9?

### ISSUE THREAD

**Issue by risusinf** [JamesLMilner/terra-draw#386]
Drawing in polygon mode doesn't animate geometry state on mousemove and rather works in blind step-by-step fashion.

Try drawing a polygon: https://jsbin.com/sehojajafo/edit?html,output

Short clip:
https://github.com/user-attachments/assets/125be4a1-0f03-4497-97ad-6907bbc1b85d

**Comment by JamesLMilner** [comment]
Hey @risusinf - I can't reproduce this locally or on terradraw.io which is using `1.0.0-beta.9` (https://github.com/JamesLMilner/terra-draw-website). Is it possible this is an issue with https://github.com/watergis/maplibre-gl-terradraw as it looks like you're using it? Perhaps @JinIgarashi knows more.

**Comment by JinIgarashi** [comment]
Hi @JamesLMilner , I realized the following setting in the plugin cause the issue of polygon mode behaviour. It worked with previous terradraw, I think. Do you have any idea for this?

```
		polygon: new TerraDrawPolygonMode({
			// eslint-disable-next-line @typescript-eslint/ban-ts-comment
			// @ts-ignore
			validation: (feature: MapGeoJSONFeature, e: { updateType: string }) => {
				const updateType = e.updateType;
				if (updateType === 'finish' || updateType === 'commit') {
					// eslint-disable-next-line @typescript-eslint/ban-ts-comment
					// @ts-ignore
					return ValidateNotSelfIntersecting(feature);
				}
				return true;
			}
		}),
```

**Comment by JinIgarashi** [comment]
validation example is documented [here](https://github.com/JamesLMilner/terra-draw/blob/main/guides/4.MODES.md#validation-in-drawing-modes). It is same with the plugin setting.

**Comment by JinIgarashi** [comment]
<img width="684" alt="image" src="https://github.com/user-attachments/assets/6e90339f-e862-41c3-86d0-b18a2ce166f3" />

I see now `ValidateNotSelfIntersecting` returns `{valid: boolean}`. 

It works with the below code

```
		polygon: new TerraDrawPolygonMode({
			// eslint-disable-next-line @typescript-eslint/ban-ts-comment
			// @ts-ignore
			validation: (feature: MapGeoJSONFeature, e: { updateType: string }) => {
				const updateType = e.updateType;
				if (updateType === 'finish' || updateType === 'commit') {
					// eslint-disable-next-line @typescript-eslint/ban-ts-comment
					// @ts-ignore
					return ValidateNotSelfIntersecting(feature);
				}
				return {valid: true};
			}
		}),
```

documentation needs to be updated.

**Comment by JinIgarashi** [comment]
@risusinf please try v0.6.6 for the plugin.

**Comment by risusinf** [comment]
I had the same problem in my app which doesn't use the controls plugins but rather my own implementation, so i assumed it couldn't be its fault.

So if i'm getting this right recent changes to validation function are breaking existing code that already uses that function and i need to update it in order to get it working again.

Bumping to 1.6.6 in the bin solved it.
Thanks everyone.
