### ISSUE TITLE
Suggested useful methods.

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#39]
## getFeatureAtMouseEvent
A method to know if the mouse is over a feature and get it if so.

Currently this method could be easily implemented in the select mode like.
```
        getFeatureAtMouseEvent(event: TerraDrawMouseEvent){
		return this.featuresAtMouseEvent.find(
			event,
			this.selected.length > 0
		).clickedFeature;
	}
```

But I think that for the user of terra draw it would be better to have this implementation in the root terra draw class.
https://github.com/JamesLMilner/terra-draw/blob/main/src/terra-draw.ts

And also not pass a `TerraDrawMouseEvent` but a `PointerEvent | MouseEvent`, (and internally using `getDrawEventFromEvent` of the common adapter to make the conversion to `TerraDrawMouseEvent` ).

## reRender method
A method to get a snapshot, clear everything, and add those features again. Useful if for example in the parent map we updated the whole style and get rid of the sources and layers that terra draw created, this way we could call this method and everything would be restored.

This method could be implemented in the root/main class of terra draw
https://github.com/JamesLMilner/terra-draw/blob/main/src/terra-draw.ts

```
	public reRender() {
		const currentMode = this._modes[this._mode.mode];

		// 1- stop current mode to remove midpoints, vertexes or unwanted features
		if (currentMode){
			currentMode.stop();
		}

		// 2- now we get only the wanted features
		const snapshot = this.getSnapshot();

		// 3- basically remove everything, store, sources and layers
		this.clear();

		// 4- apply stored snapshot
		this.addFeatures(snapshot);

		// 5- start once again the same mode the user was in
		if (currentMode){
			currentMode.start();
		}
	}
```

This method would imply that we can no longer assume all layers and sources are there, so for example in mapbox gl adapter

https://github.com/JamesLMilner/terra-draw/blob/65ba076741e610a1b9c9eaa6baa5d71d4a1a85b8/src/adapters/mapbox-gl.adapter.ts#L35-L45

We would need ensure each source/layer is there before remove/modify it, like
`if (this._map.getLayer(id)) this._map.removeLayer(id);`

The places we would need to add this validation are:
https://github.com/JamesLMilner/terra-draw/blob/65ba076741e610a1b9c9eaa6baa5d71d4a1a85b8/src/adapters/mapbox-gl.adapter.ts#L37
https://github.com/JamesLMilner/terra-draw/blob/65ba076741e610a1b9c9eaa6baa5d71d4a1a85b8/src/adapters/mapbox-gl.adapter.ts#L42
https://github.com/JamesLMilner/terra-draw/blob/65ba076741e610a1b9c9eaa6baa5d71d4a1a85b8/src/adapters/mapbox-gl.adapter.ts#L44
https://github.com/JamesLMilner/terra-draw/blob/65ba076741e610a1b9c9eaa6baa5d71d4a1a85b8/src/adapters/mapbox-gl.adapter.ts#L165-L168
https://github.com/JamesLMilner/terra-draw/blob/65ba076741e610a1b9c9eaa6baa5d71d4a1a85b8/src/adapters/mapbox-gl.adapter.ts#L400

**Comment by JamesLMilner** [comment]
Hi @alanOracle - as always appreciate your enthusiasm. Thanks for raising these I will take a look at seeing how feasible these would be. First priority is looking at the drag situation that you raised in #37 as I think it is a sensible point.

**Comment by JamesLMilner** [comment]
I'm going to close this in favour of specific issues where appropriate for these features.
