### ISSUE TITLE
Bugs and Suggestions

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#44]
Hi its me again hope you are doing great, I have a new report. Thanks.
## Moving too fast in select mode 
If you abruptly drag a feature, you can get out of it.
And if you move close to a vertex, you can move it.
All of this without releasing the left mouse button.

![dragFast](https://github.com/JamesLMilner/terra-draw/assets/132691171/8f372cd4-51c5-42aa-8917-8b89fd466171)

This happens because terradraw validate if the mouse is inside the figure each time we drag before moving it, we could change that validation to do it only when dragging starts, not every time 'drag' event is fired. And once we know the user started with a valid position we can move it wherever the event is saying.

Proposed Solution:
Preserve the user choice to drag the whole feature or just a vertex when start dragging (onDragStart), and just keep updating that option (onDrag), this way no matter how fast the user moves, as long as it does not release the button terradraw will only update the initial choice.

Check if the user wants to drag a vertex or the whole feature
https://github.com/JamesLMilner/terra-draw/compare/main...alanOracle:terra-draw:studio-approach?expand=1#diff-66b8b33e810bc4e27d8af887cbf5f6415b2ad6156d33ed947972cb459ca94e3bR475-R497

Then on drag validate which type of drag we are doing and ONLY do that one.
https://github.com/JamesLMilner/terra-draw/compare/main...alanOracle:terra-draw:studio-approach?expand=1#diff-66b8b33e810bc4e27d8af887cbf5f6415b2ad6156d33ed947972cb459ca94e3bR586

## Mapbox/Maplibre Performance in select mode
Although now terra draw has a great performance in maplibre/mapbox there is still a lot of lag when in select mode.
This is likely because it has to update 3 layers (polygon, outline and points) each time we drag anything.

So first of all I know that terra draw wants to keep the same design and style across all adapters so maybe this is not the best solution.

But here it is, basically an approach to this could be to avoid updating the points layer when on select mode.

This could be done by checking if the user want to drag the whole feature, then onDragStart delete all selection and mid points, and restore them onDragEnd so that when the user drags would only see the polygon moving without any points.

In the other hand if the user want to drag only a vertex then delete all midpoints (because I discovered that all of them are sent to render method no matter if they are actually updated or not) and also delete the single selection point that the user selected, this way we wont update the points layer since the remaining selection points are not moving anywhere and could serve as reference.

Delete selection and midpoints onDragStart
https://github.com/JamesLMilner/terra-draw/compare/main...alanOracle:terra-draw:studio-approach?expand=1#diff-66b8b33e810bc4e27d8af887cbf5f6415b2ad6156d33ed947972cb459ca94e3bR499-R533

Re-construct points onDragEnd
https://github.com/JamesLMilner/terra-draw/compare/main...alanOracle:terra-draw:studio-approach?expand=1#diff-66b8b33e810bc4e27d8af887cbf5f6415b2ad6156d33ed947972cb459ca94e3bR621-R624

## Features are not updated when there's a change in style
This happens in maplibre/mapbox adapter since style changes passes an array of all features as unchanged to render method.
Which now for performance reasons wont do anything if everything is unchanged.

Proposed Solution:
Just as we have a `deletionOccured` in render mode of, we could also have somthing like
`const styleChangeOccured = Object.values(this.changedIds).every(change=>!change) && changes.unchanged.length > 0;`
To force the update of the features if so.

For example
https://github.com/JamesLMilner/terra-draw/compare/main...alanOracle:terra-draw:studio-approach?expand=1#diff-b0a667c9d571e4bfe0433d3e4fb6fbe181bec821b260b5250e1b6dffd073de99R366-R373

## Error when quitting terradraw while have something selected
To reproduce it:
Using maplibre adpater, select a feature, then call the stop method of terra draw (which deletes everything).

You will see all features being deleted for a fraction of second and then the selected feature will appear again but without any points and not being able to modify it.

This happens because when we call the stop method of the main terradraw class then it correctly call the cleanUp method of the mode which will delete all selection and midpoints of the figure, but because the render method is waiting 16 milliseconds to do the update and as it waits we delete all features then at the end we would see only the selected feature again on the map.

Proposed Solution:
One way it can be solved its just by removing the debounce of the render method of the mapbox adapter

Removing debounce rendering
https://github.com/JamesLMilner/terra-draw/compare/main...alanOracle:terra-draw:studio-approach?expand=1#diff-b0a667c9d571e4bfe0433d3e4fb6fbe181bec821b260b5250e1b6dffd073de99L295-L303

## Avoid error when moving figure to the edges of the map
Currently there's an error when you move a figure outside the current map in maplibre adapter (when you have setRenderWorldCopies ON).

Also it would be nice to prevent figures going outside the latitude range (-90,90).

For example validating -85 , 85 in lat
https://github.com/JamesLMilner/terra-draw/compare/main...alanOracle:terra-draw:studio-approach?expand=1#diff-ace904c8e4070082cedc13adb31cfeb6a24851b1aea7ac5bc6304a6787903b27R68-R86

## Prevent right click
It would be nice to have an option to ignore all right clicks so that it doesn't mix with other actions to be performed outside terradraw

**Comment by JamesLMilner** [comment]
@alanOracle thanks for raising all these - I have been looking into some of them. In future if possible can I kindly ask you to raise the issues individually so I can better keep track of them? No need to do it for these as I will create seperate tickets where necessary but just a polite request for the future!

**Comment by JamesLMilner** [comment]
Hey @alanOracle thanks again for raising these. I think they are either resolved (use the latest version `0.0.1-alpha.38`) or there is a separate open issue for them now, except your last point about preventing right click. Could you create a separate issue with more information with what you mean?

Also I noticed the typings for setModeStyling were wrong, you need to pass the styling interface that is provided to the initialise the mode, so for example for polygon you need to pass a partial PolygonStyling object:

https://github.com/JamesLMilner/terra-draw/blob/be0f8f07f7d1043cd3bd6fa65c17edd81e1f9bdf/src/modes/polygon/polygon.mode.ts#L26
