### ISSUE TITLE
Drawing Different Colored Polygons

### ISSUE THREAD

**Issue by UncatchableAlex** [JamesLMilner/terra-draw#59]
I am using MapLibre and TerraDrawMapLibreGLAdapter. I want to draw many polygons on my map and have each be a different color. I have already tried a few things:

1.) Defining multiple modes with distinct TerraDrawPolygonMode objects (each with a unique styling) in the constructor for my TerraDraw object, and then switching modes before drawing each polygon with [setMode](https://jameslmilner.github.io/terra-draw/classes/TerraDraw.html#setMode). This didn't work. Any mode not keyed with "polygon" will not allow the user to draw anything. This behavior is strange because in the [docs](https://jameslmilner.github.io/terra-draw/classes/TerraDraw.html) the constructor definition for TerraDraw is given as:
``new TerraDraw(options: {
    adapter: TerraDrawAdapter;
    modes: {
        [mode: string]: TerraDrawBaseDrawMode<any>;
    };
}): TerraDraw``
which seems to imply that the key for each mode can be any string (when in reality, in order to draw a polygon, the key must be the string literal "polygon").

2.) Using a single polygon mode and calling setModeStyles on my TerraDraw object with a new styling before drawing the next polygon. This causes every polygon to change color. I guess this makes sense, but it's not what I'm after.

3.) Using separate TerraDraw objects, each with a polygon mode with unique styling and switching between them. Using one TerraDraw object to draw seems to erase all previously drawn polygons from other TerraDraw objects.

I also tried playing around with the render() method on my TerraDrawMapLibreGLAdapter. I didn't get anywhere with that either. I'm new to Terra Draw and I'm not sure where to go from here. Any suggestions would be appreciated.

Thank you, guys.

**Comment by JamesLMilner** [comment]
Hey @UncatchableAlex thanks  for raising this issue! I appreciate your feed back and detailed message.

Firstly, you are right in saying at the moment this isn't really possible with Terra Draw. _However_ I would like to explore how to make this happen - one idea I've had is allow users to be able to override any given feature with a custom styling object which would let them change the style of the feature at any time. One potential issue with this approach is you might get some 'flashing' as the default styles get overridden with the custom ones - I'd have to check if this is actually a problem in reality. Another approach could be custom styling function based which could allow users to style features however they want (i.e. random colours). This might be the more sensible option as it is very extensible and relatively simple.

I would be interested to hear your feedback on how you would see yourself styling the polygons - let me know what you think.

Also with point 1) in your message, I agree this is potentially a bit cumbersome to provide the mode type in the object. I may change it at some point to just be an array to simplify things.

**Comment by JamesLMilner** [comment]
Just to follow up @UncatchableAlex  I think I have a little demo of this working locally. It could work like this:

```typescript
function getRandomColor() {
          const letters = '0123456789ABCDEF';
          let color = '#';
          for (let i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
          }
          return color;
}
          
// ... later on          

		polygon: new TerraDrawPolygonMode({
			styles: {
				fillColor: (_) => getRandomColor()
			},
		}),
```

would that work for you?

**Comment by UncatchableAlex** [comment]
Hey @JamesLMilner! For my particular use case, I don't need to be able to change the styling of features after they have been drawn. I would like to select a styling for the feature before it gets drawn, draw the feature with that styling, and never change the styling thereafter.

I'm a bit new to web dev and mapping in general, but I would definitely be down to make a fork of this repo and maybe make a pull request. If you don't have a specific implementation in mind, then I'd love to pitch in (or try, at least).

As a side note, I love the ability to prevent self-intersections in polygon mode. I feel like this functionality is missing from select mode, however. It would be nice to prevent users from editing existing non-self-intersecting polygons into self-intersecting ones. Is this worth making another issue thread over?

**Comment by JamesLMilner** [comment]
Hey @UncatchableAlex thanks for the details. Your use case makes a lot of sense and I understand what you are trying to do - let me have a think on it. I have a potential solution but I am just wanting to make sure it is the right one, as for your use case it is arguably a bit 'verbose', however it is extensible and would allow other users to do perform different/complex styling changes if they needed. Here's how my suggested solution would work if we implemented it via styling functions:

```typescript

// Function to generate a random hex color - can adjust as needed
function getRandomColor() {
	const letters = "0123456789ABCDEF";
	let color = "#";
	for (let i = 0; i < 6; i++) {
		color += letters[Math.floor(Math.random() * 16)];
	}
	return color;
}

// Cache for each feature id mapped to a hex color string
const colorCache: Record<string, string> = {};

const draw = new TerraDraw({
	adapter: new TerraDrawMapboxGLAdapter({
		map, // Assume this is defined further up
		coordinatePrecision: 9,
	}),
	modes: {
		polygon: new TerraDrawPolygonMode({
			styles: {
				fillColor: (feature) => {
					const id = feature.id;

					// Get the color from the cache or generate a new one
					colorCache[id] = colorCache[id] || getRandomColor();
					return colorCache[id];
				},
			},
		}),
	}
});

// Ensure the cache is clead up on deletion of features
draw.on("delete", (ids) => ids.forEach((id) => delete cache[id]));

```

I'm always excited for people to get involved with Terra Draw - this issue may be a tough one to raise a PR for because I think we really need to get the API right.  I'd be happy to chat with you more about it to try and figure something out that works for you though, maybe starting with what you think of the above? Feel free to share any code snippets or ideas you have about the API. 

I would actually say the dragging intersection prevention you suggested would be a great separate issue and PR candidate though if you were interested! It'd be a great addition and nicely self contained for a PR.

**Comment by JamesLMilner** [comment]
@UncatchableAlex sorry this would marked as closed automatically when I tagged the issue in the Pull Request. This should be achievable now with the code above! Let me know if it works for you? You can of course use a different hex code generation code snippet to fit your needs. This is a good article on some different approaches to generating hex colors: https://martin.ankerl.com/2009/12/09/how-to-create-random-colors-programmatically/

**Comment by UncatchableAlex** [comment]
Sorry for being absent. I just implemented the function-based styling in my project and it looks great! Thank you for all your help!
