### ISSUE TITLE
Dragging selection points outside map

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#61]
Hi @JamesLMilner I have a set of issues I will post individually, hope you are doing well.

Currently there's a validation of the features position to keep them inside the lat and lng range. This is being done when you drag the whole feature, but it is possible to drag a single vertex of a feature (selection point) outside this boundaries.

**Comment by JamesLMilner** [comment]
Thanks @alanOracle 

Resolved in `0.0.1-alpha.44`. Long term it would be nice to have better handling of antimeridian crossings.
