### ISSUE TITLE
Bug: Generation of Invalid Snapshots due to NO limiting precision

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#62]
You can for example draw a polygon , then drag it. 

The action of drag it will cause that the geometry of the feature will be expressed as decimal numbers potentially exceeding the coordinatePrecision. There's no problem noticeable right away but if you get a snapshot and later try to use that snapshot to replicate the previous state you will get an error.

The validation could be done here.

https://github.com/JamesLMilner/terra-draw/blob/56a6960fc8ca87742760c284a6269f759be97372/src/modes/select/behaviors/drag-feature.behavior.ts#L116

To be something like this:
`updatedCoords[i] = [limitPrecision(updatedLng, this.coordinatePrecision), limitPrecision(coordinate[1] - delta[1], this.coordinatePrecision)];`

Of course we would need to import limitPrecision helper function.

Thanks for the constant updates hope this is helpful.

**Comment by JamesLMilner** [comment]
Thanks @alanOracle

Resolved in 0.0.1-alpha.44. Should no longer create extra precision.
