### ISSUE TITLE
Cannot select points in Google Maps Adapter when view is rotated/tilted

### ISSUE THREAD

**Issue by anderswi** [JamesLMilner/terra-draw#76]
When rotating/tilting a (vector) map using the Google Maps adapter, selection breaks. It seems like `project` and `unproject` in google-maps-adapter does not take rotation/tilting into account.

I did a quick test with replacing the project/unproject code with `projection.fromLatLngToContainerPixel` and `projection.fromContainerPixelToLatLng` which seems to work better, but I'm unsure if there's reasons not to use those instead of the custom projection code?

**Comment by JamesLMilner** [comment]
Hey @anderswi - thanks for raising this. I haven't had a chance to experiment with Terra Draw + vector Google Maps. I can see why this would be an issue though. 

I'd imagine that your observation about rotation and tilt not being take into account is correct. Let me see if I can find some time to investigate.

I think this is partially related to #23 as when you move to 3D rendering these types of issues are crop up.

**Comment by anderswi** [comment]
Hi James,

I took a stab at fixing this, hope you find it useful. :)

**Comment by JamesLMilner** [comment]
Hey @anderswi thanks for this! Appreciate your input. Unfortunately I am on holiday until the 18th of September so won't be able to properly review this until then. When I'm back I will get straight on it.

**Comment by anderswi** [comment]
No worries, enjoy your holiday!
