### ISSUE TITLE
Ignored click due to microDrags

### ISSUE THREAD

**Issue by alanOracle** [JamesLMilner/terra-draw#77]
Hi @JamesLMilner hope you are doing great. 👍

Currently if you are drawing too fast you can accidently drag a little bit which causes that the event gets interpreted as a a drag instead of a click (which most of the times is incorrect since we were trying to draw). This is already into consideration with the microDrags, which is a range that can even be customized:

https://github.com/JamesLMilner/terra-draw/blob/a51d2781b8a801948d545bae9525808e1efdad0e/src/adapters/common/base.adapter.ts#L118-L122

The problem is that this happens also when you are selecting. You can select from one feature to another and sometimes you would get the sensation that terra draw is not responding, but the real thing is that the event you thought was a click is actually being interpreted as a drag.

To reproduce this:
- Very quickly change the selected feature from one to another and you could sometime get into this error
- You could do a very slow movement of the mouse 
- Basically do some movement in between the "pointerDown" and the "pointerUp" events.

And the reason is here:

https://github.com/JamesLMilner/terra-draw/blob/a51d2781b8a801948d545bae9525808e1efdad0e/src/adapters/common/base.adapter.ts#L114-L130

If you are not drawing then the microDrag would be computed using the `_minPixelDragDistance` (which by default is 1) instead of the `_minPixelDragDistanceDrawing`.

So you could say that customizing `_minPixelDragDistance` to a larger number could solve the problem (let say 40). And it does!, now you can even drag a little bit and the event gets interpreted as a click (which is nice and preferred). 

But if you go this way the more you increase the value the more you would need to move/drag for example a selection point or the actual feature to actually move/drag it.

## Proposal

The proposal is then to do the micro drag evaluation always excepting when we know the user wants to drag either a selection point or the whole feature.

### How do we know when the user wants to drag?.

For that we would need to know if the "pointerDown" event would be interpreted as drag if given to "onDragStart" of the select mode.

Because the evaluation is being done in the base adapter the only interface we have with the mode is the `_currentModeCallbacks` to later get the state like `_currentModeCallbacks.getState();`. We could use the "selected" state, that I think is not being used anywhere to tell the base adapter when to avoid the microdrag evaluation. For that we could add an optional method that would only be used in select mode, called for example `onPointerDown` which could be called in the "pointerDown" handler:

https://github.com/JamesLMilner/terra-draw/blob/a51d2781b8a801948d545bae9525808e1efdad0e/src/adapters/common/base.adapter.ts#L41-L67

And the new `onPointerDown` method could be very similar to the onDragStart method of the select mode

https://github.com/JamesLMilner/terra-draw/blob/a51d2781b8a801948d545bae9525808e1efdad0e/src/modes/select/select.mode.ts#L518-L575

Just only focusing on the drag stuff like:

```
onPointerDown(event: TerraDrawMouseEvent){
		// We only need to stop the map dragging if
		// we actually have something selected
		if (!this.selected.length) {
			return;
		}

		// If the selected feature is not draggable
		// don't do anything
		const properties = this.store.getPropertiesCopy(this.selected[0]);
		const modeFlags = this.flags[properties.mode as string];
		const draggable =
			modeFlags &&
			modeFlags.feature &&
			(modeFlags.feature.draggable ||
				(modeFlags.feature.coordinates &&
					modeFlags.feature.coordinates.draggable));


		if (!draggable) {
			return;
		}

		const selectedId = this.selected[0];
		const draggableCoordinateIndex = this.dragCoordinate.getDraggableIndex(
			event,
			selectedId
		);

		if (
			modeFlags &&
			modeFlags.feature &&
			modeFlags.feature.coordinates &&
			modeFlags.feature.coordinates.draggable &&
			draggableCoordinateIndex !== -1
		) {
			this.setSelected();
			return;
		}

		if (
			modeFlags &&
			modeFlags.feature &&
			modeFlags.feature.draggable &&
			this.dragFeature.canDrag(event, selectedId)
		) {
			this.setSelected();
			return;
		}
	}
```

And as you may noticed is calling the also new `setSelected();` which would change the state to "selected"

This way on the base adapter instead of doing a...

https://github.com/JamesLMilner/terra-draw/blob/a51d2781b8a801948d545bae9525808e1efdad0e/src/adapters/common/base.adapter.ts#L114

We would only need something like this

`if (modeState !== "selected") {`

And forgot about the else.

I'm not considering the extra necessary work to implement for example the setSelected method but I think you get an idea

Here's the changes I would do to achieve that.
https://github.com/alanOracle/terra-draw/commit/fca111427d13e4a719cf4e22512232b2cd8578fc

Sorry for the large explanation. And thanks.

**Comment by JamesLMilner** [comment]
Hey @alanOracle - thanks for raising this detailed issue - it's appreciated! I will look into a good way to resolve this when I get some more time.

**Comment by JamesLMilner** [comment]
I've attempted to fix this by having a new state called `selecting` and doing a new micro-drag branch where you can return early based on a customisable threshold (`minPixelDragDistanceSelecting`).

**Comment by alanOracle** [comment]
Thanks I'll definitely take a look at it.
