### ISSUE TITLE
The "finish" event is not triggered when the drag end

### ISSUE THREAD

**Issue by gdnwr** [JamesLMilner/terra-draw#80]
After selecting and dragging a point, it will trigger the "change" event, but the "finish" event is not triggered when the drag end.
    I would like to perform some specific actions after the drag end. Can you trigger the "finish" event after the drag end, or should we introduce a new event for this purpose?

**Comment by JamesLMilner** [comment]
Hey @gdnwr - thanks for raising this! I think this sounds like a reasonable request. I think calling onFinish on finishing dragging a coordinate or whole feature would probably be the way to go about this. Let me look into it.
