### ISSUE TITLE
Update TypeScript to 5.2.2

### ISSUE THREAD

**Issue by JamesLMilner** [JamesLMilner/terra-draw#94]
This ticket is to cover upgrading from TypeScript 5.0.3 to 5.2.2. This will also cover updating any new places where the types fail due to the change.

To do this we can do:

```
npm install --save-dev typescript@5.2.2
```

and then check for any type check failures on build:

```
npm run build
```

Seeing if there any errors and if so resolving them, then raising the change with a PR.

**Comment by amitx13** [comment]
Hey @JamesLMilner sir can i work on this

**Comment by JamesLMilner** [comment]
Hey @amitx13 - yeah for sure! I can assign you :)

**Comment by sidling1** [comment]
Hey can i do this ?

**Comment by JamesLMilner** [comment]
@sidling1 I have assigned you :) Feel free to have a go at resolving this.

**Comment by sidling1** [comment]
![image](https://github.com/JamesLMilner/terra-draw/assets/92554460/ae02a812-12a9-4bc7-83c7-7e3508608775)

@JamesLMilner I think there were no error , the build was succesfull. Can you look at the picture and confirm once , Then i can do a PR.

**Comment by JamesLMilner** [comment]
Thanks @sidling1 - marked this as complete now your PR is merged.
