### ISSUE TITLE
'nocheck' test scripts do not work on Windows

### ISSUE THREAD

**Issue by AndrewADev** [JamesLMilner/terra-draw#99]
Currently, the [`test:nocheck`](https://github.com/JamesLMilner/terra-draw/blob/main/package.json#L14) and [`test:nocheck:coverage`](https://github.com/JamesLMilner/terra-draw/blob/main/package.json#L15) scripts will fail on Windows due to the use of unsupported syntax for environment variables:

```shell
$ npm run test:nocheck

> terra-draw@0.0.1-alpha.48 test:nocheck
> NO_CHECK=true jest --config jest.config.ts

'NO_CHECK' is not recognized as an internal or external command,
operable program or batch file.
```

![image](https://github.com/JamesLMilner/terra-draw/assets/2937540/ef67a8a7-5f32-475c-97ba-9eabab0cc2bc)

As the the [`NO_CHECK` variable is only used in the `jest.config.js` file](https://github.com/JamesLMilner/terra-draw/blob/main/jest.config.ts#L3), perhaps we could simply provide alternate jest configs in the commands instead, e.g. `jest.config.js` and `jest.nocheck.config.js` or similar via the `--config` argument?

#### Workaround

It's not exactly the same use-case, but I've been using the Jest command for running only on changed files to avoid running the full suite (which takes a while):
```shell
$ npx jest -o
```

**Comment by JamesLMilner** [comment]
Thanks for raising this @AndrewADev - I appreciate now that this wouldn't work on Windows! One solution could be either to create a new config file, or to use something like `cross-env`. Separate config files would probably be better I think although there I was trying to avoid too many files at the top level.

I'm happy to raise a PR for separate configs, or if you would like the honours then just let me know :)

**Comment by AndrewADev** [comment]
I first thought of `cross-env` as well, but it seems it has not been updated in a while and is now archived. I am not aware of an alternative at the moment, but that would of course work too, if you have something in mind.

About the top-level files, it would also be possible to group things like config files in a subdirectory if they get to be too many (disadvantage being that they would likely need to be explicitly specified always, instead of automatically detected).

A PR sounds great, thanks! Happy to take a look to verify (can also do the PR, if you get busy)

**Comment by JamesLMilner** [comment]
Yeah looks like cross-env isn't actively maintained any more. Let's go with the custom jest config! 

Yeah unfortunately many of them can't live in separate directories to my understanding (i.e. package.json, package-lock.json, .gitignore, .npmignore) so not sure if it would help too much. However I think one more file in this instance wouldn't do any harm.

I will aim to get to this soon as it's not a huge change. I'll keep you posted!
